# resolve-type-names: false

class ::Access < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Access, ::Access::ActiveRecord_Relation, ::String]

  module ::Access::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def accessed_at: () -> ::ActiveSupport::TimeWithZone?

    def accessed_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

    def accessed_at?: () -> bool

    def accessed_at_changed?: () -> bool

    def accessed_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def accessed_at_will_change!: () -> void

    def accessed_at_was: () -> ::ActiveSupport::TimeWithZone?

    def accessed_at_previously_changed?: () -> bool

    def accessed_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def accessed_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def accessed_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def accessed_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def accessed_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_accessed_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_accessed_at?: () -> bool

    def will_save_change_to_accessed_at?: () -> bool

    def restore_accessed_at!: () -> void

    def clear_accessed_at_change: () -> void

    def accessed_at_before_type_cast: () -> ::Time?

    def accessed_at_for_database: () -> ::Time?

    def board_id: () -> ::String

    def board_id=: (::String) -> ::String

    def board_id?: () -> bool

    def board_id_changed?: () -> bool

    def board_id_change: () -> [ ::String?, ::String? ]

    def board_id_will_change!: () -> void

    def board_id_was: () -> ::String?

    def board_id_previously_changed?: () -> bool

    def board_id_previous_change: () -> ::Array[::String?]?

    def board_id_previously_was: () -> ::String?

    def board_id_before_last_save: () -> ::String?

    def board_id_change_to_be_saved: () -> ::Array[::String?]?

    def board_id_in_database: () -> ::String?

    def saved_change_to_board_id: () -> ::Array[::String?]?

    def saved_change_to_board_id?: () -> bool

    def will_save_change_to_board_id?: () -> bool

    def restore_board_id!: () -> void

    def clear_board_id_change: () -> void

    def board_id_before_type_cast: () -> ::String

    def board_id_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def involvement: () -> ::String

    def involvement=: (::String) -> ::String

    def involvement?: () -> bool

    def involvement_changed?: () -> bool

    def involvement_change: () -> [ ::String?, ::String? ]

    def involvement_will_change!: () -> void

    def involvement_was: () -> ::String?

    def involvement_previously_changed?: () -> bool

    def involvement_previous_change: () -> ::Array[::String?]?

    def involvement_previously_was: () -> ::String?

    def involvement_before_last_save: () -> ::String?

    def involvement_change_to_be_saved: () -> ::Array[::String?]?

    def involvement_in_database: () -> ::String?

    def saved_change_to_involvement: () -> ::Array[::String?]?

    def saved_change_to_involvement?: () -> bool

    def will_save_change_to_involvement?: () -> bool

    def restore_involvement!: () -> void

    def clear_involvement_change: () -> void

    def involvement_before_type_cast: () -> ::String

    def involvement_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def user_id: () -> ::String

    def user_id=: (::String) -> ::String

    def user_id?: () -> bool

    def user_id_changed?: () -> bool

    def user_id_change: () -> [ ::String?, ::String? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> ::String?

    def user_id_previously_changed?: () -> bool

    def user_id_previous_change: () -> ::Array[::String?]?

    def user_id_previously_was: () -> ::String?

    def user_id_before_last_save: () -> ::String?

    def user_id_change_to_be_saved: () -> ::Array[::String?]?

    def user_id_in_database: () -> ::String?

    def saved_change_to_user_id: () -> ::Array[::String?]?

    def saved_change_to_user_id?: () -> bool

    def will_save_change_to_user_id?: () -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def user_id_before_type_cast: () -> ::String

    def user_id_for_database: () -> ::String

    def account_id: () -> ::String

    def account_id=: (::String) -> ::String

    def account_id?: () -> bool

    def account_id_changed?: () -> bool

    def account_id_change: () -> [ ::String?, ::String? ]

    def account_id_will_change!: () -> void

    def account_id_was: () -> ::String?

    def account_id_previously_changed?: () -> bool

    def account_id_previous_change: () -> ::Array[::String?]?

    def account_id_previously_was: () -> ::String?

    def account_id_before_last_save: () -> ::String?

    def account_id_change_to_be_saved: () -> ::Array[::String?]?

    def account_id_in_database: () -> ::String?

    def saved_change_to_account_id: () -> ::Array[::String?]?

    def saved_change_to_account_id?: () -> bool

    def will_save_change_to_account_id?: () -> bool

    def restore_account_id!: () -> void

    def clear_account_id_change: () -> void

    def account_id_before_type_cast: () -> ::String

    def account_id_for_database: () -> ::String
  end
  include ::Access::GeneratedAttributeMethods
  module ::Access::GeneratedAliasAttributeMethods
    include ::Access::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Access::GeneratedAliasAttributeMethods

  def account: () -> ::Account
  def account=: (::Account?) -> ::Account?
  def reload_account: () -> ::Account?
  def build_account: (untyped) -> ::Account
  def create_account: (untyped) -> ::Account
  def create_account!: (untyped) -> ::Account
  def board: () -> ::Board
  def board=: (::Board?) -> ::Board?
  def reload_board: () -> ::Board?
  def build_board: (untyped) -> ::Board
  def create_board: (untyped) -> ::Board
  def create_board!: (untyped) -> ::Board
  def user: () -> ::User
  def user=: (::User?) -> ::User?
  def reload_user: () -> ::User?
  def build_user: (untyped) -> ::User
  def create_user: (untyped) -> ::User
  def create_user!: (untyped) -> ::User
  module ::Access::GeneratedAssociationMethods
  end
  include ::Access::GeneratedAssociationMethods

  def access_only!: () -> bool
  def access_only?: () -> bool
  def watching!: () -> bool
  def watching?: () -> bool
  def self.involvements: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
  def self.access_only: () -> ::Access::ActiveRecord_Relation
  def self.not_access_only: () -> ::Access::ActiveRecord_Relation
  def self.watching: () -> ::Access::ActiveRecord_Relation
  def self.not_watching: () -> ::Access::ActiveRecord_Relation
  def self.ordered_by_recently_accessed: () -> ::Access::ActiveRecord_Relation

  module ::Access::GeneratedRelationMethods
    def involvements: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

    def access_only: () -> ::Access::ActiveRecord_Relation

    def not_access_only: () -> ::Access::ActiveRecord_Relation

    def watching: () -> ::Access::ActiveRecord_Relation

    def not_watching: () -> ::Access::ActiveRecord_Relation

    def ordered_by_recently_accessed: () -> ::Access::ActiveRecord_Relation
  end

  class ::Access::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Access]
    include ::Access::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Access, ::String]
  end

  class ::Access::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Access]
    include ::Access::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Access, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Access
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Access]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Access
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Access]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Access
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Access]
    def reload: () -> ::Array[::Access]

    def replace: (::Array[::Access]) -> void
    def delete: (*::Access | ::String) -> ::Array[::Access]
    def destroy: (*::Access | ::String) -> ::Array[::Access]
    def <<: (*::Access | ::Array[::Access]) -> self
    def prepend: (*::Access | ::Array[::Access]) -> self
  end
end
