# resolve-type-names: false

class ::Entropy < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Entropy, ::Entropy::ActiveRecord_Relation, ::String]

  module ::Entropy::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def auto_postpone_period: () -> ::Integer

    def auto_postpone_period=: (::Integer) -> ::Integer

    def auto_postpone_period?: () -> bool

    def auto_postpone_period_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def auto_postpone_period_change: () -> [ ::Integer?, ::Integer? ]

    def auto_postpone_period_will_change!: () -> void

    def auto_postpone_period_was: () -> ::Integer?

    def auto_postpone_period_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def auto_postpone_period_previous_change: () -> ::Array[::Integer?]?

    def auto_postpone_period_previously_was: () -> ::Integer?

    def auto_postpone_period_before_last_save: () -> ::Integer?

    def auto_postpone_period_change_to_be_saved: () -> ::Array[::Integer?]?

    def auto_postpone_period_in_database: () -> ::Integer?

    def saved_change_to_auto_postpone_period: () -> ::Array[::Integer?]?

    def saved_change_to_auto_postpone_period?: () -> bool

    def will_save_change_to_auto_postpone_period?: () -> bool

    def restore_auto_postpone_period!: () -> void

    def clear_auto_postpone_period_change: () -> void

    def auto_postpone_period_before_type_cast: () -> ::Integer

    def auto_postpone_period_for_database: () -> ::Integer

    def container_id: () -> ::String

    def container_id=: (::String) -> ::String

    def container_id?: () -> bool

    def container_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def container_id_change: () -> [ ::String?, ::String? ]

    def container_id_will_change!: () -> void

    def container_id_was: () -> ::String?

    def container_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def container_id_previous_change: () -> ::Array[::String?]?

    def container_id_previously_was: () -> ::String?

    def container_id_before_last_save: () -> ::String?

    def container_id_change_to_be_saved: () -> ::Array[::String?]?

    def container_id_in_database: () -> ::String?

    def saved_change_to_container_id: () -> ::Array[::String?]?

    def saved_change_to_container_id?: () -> bool

    def will_save_change_to_container_id?: () -> bool

    def restore_container_id!: () -> void

    def clear_container_id_change: () -> void

    def container_id_before_type_cast: () -> ::String

    def container_id_for_database: () -> ::String

    def container_type: () -> ::String

    def container_type=: (::String) -> ::String

    def container_type?: () -> bool

    def container_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def container_type_change: () -> [ ::String?, ::String? ]

    def container_type_will_change!: () -> void

    def container_type_was: () -> ::String?

    def container_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def container_type_previous_change: () -> ::Array[::String?]?

    def container_type_previously_was: () -> ::String?

    def container_type_before_last_save: () -> ::String?

    def container_type_change_to_be_saved: () -> ::Array[::String?]?

    def container_type_in_database: () -> ::String?

    def saved_change_to_container_type: () -> ::Array[::String?]?

    def saved_change_to_container_type?: () -> bool

    def will_save_change_to_container_type?: () -> bool

    def restore_container_type!: () -> void

    def clear_container_type_change: () -> void

    def container_type_before_type_cast: () -> ::String

    def container_type_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def account_id: () -> ::String

    def account_id=: (::String) -> ::String

    def account_id?: () -> bool

    def account_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def account_id_change: () -> [ ::String?, ::String? ]

    def account_id_will_change!: () -> void

    def account_id_was: () -> ::String?

    def account_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def account_id_previous_change: () -> ::Array[::String?]?

    def account_id_previously_was: () -> ::String?

    def account_id_before_last_save: () -> ::String?

    def account_id_change_to_be_saved: () -> ::Array[::String?]?

    def account_id_in_database: () -> ::String?

    def saved_change_to_account_id: () -> ::Array[::String?]?

    def saved_change_to_account_id?: () -> bool

    def will_save_change_to_account_id?: () -> bool

    def restore_account_id!: () -> void

    def clear_account_id_change: () -> void

    def account_id_before_type_cast: () -> ::String

    def account_id_for_database: () -> ::String
  end
  include ::Entropy::GeneratedAttributeMethods
  module ::Entropy::GeneratedAliasAttributeMethods
    include ::Entropy::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Entropy::GeneratedAliasAttributeMethods

  def account: () -> ::Account
  def account=: (::Account?) -> ::Account?
  def reload_account: () -> ::Account?
  def build_account: (untyped) -> ::Account
  def create_account: (untyped) -> ::Account
  def create_account!: (untyped) -> ::Account
  def container: () -> untyped
  def container=: (untyped?) -> untyped?
  def reload_container: () -> untyped?
  module ::Entropy::GeneratedAssociationMethods
  end
  include ::Entropy::GeneratedAssociationMethods

  module ::Entropy::GeneratedRelationMethods
  end

  class ::Entropy::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Entropy]
    include ::Entropy::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Entropy, ::String]
  end

  class ::Entropy::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Entropy]
    include ::Entropy::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Entropy, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Entropy
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Entropy]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Entropy
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Entropy]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Entropy
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Entropy]
    def reload: () -> ::Array[::Entropy]

    def replace: (::Array[::Entropy]) -> void
    def delete: (*::Entropy | ::String) -> ::Array[::Entropy]
    def destroy: (*::Entropy | ::String) -> ::Array[::Entropy]
    def <<: (*::Entropy | ::Array[::Entropy]) -> self
    def prepend: (*::Entropy | ::Array[::Entropy]) -> self
  end
end
