# resolve-type-names: false

class ::Filter < ::ApplicationRecord
  class ::Filter::HABTM_Tags < ::ActiveRecord::Base
    extend ::ActiveRecord::Base::ClassMethods[::Filter::HABTM_Tags, ::Filter::HABTM_Tags::ActiveRecord_Relation, top]

    module ::Filter::HABTM_Tags::GeneratedAttributeMethods
      def filter_id: () -> ::String

      def filter_id=: (::String) -> ::String

      def filter_id?: () -> bool

      def filter_id_changed?: () -> bool

      def filter_id_change: () -> [ ::String?, ::String? ]

      def filter_id_will_change!: () -> void

      def filter_id_was: () -> ::String?

      def filter_id_previously_changed?: () -> bool

      def filter_id_previous_change: () -> ::Array[::String?]?

      def filter_id_previously_was: () -> ::String?

      def filter_id_before_last_save: () -> ::String?

      def filter_id_change_to_be_saved: () -> ::Array[::String?]?

      def filter_id_in_database: () -> ::String?

      def saved_change_to_filter_id: () -> ::Array[::String?]?

      def saved_change_to_filter_id?: () -> bool

      def will_save_change_to_filter_id?: () -> bool

      def restore_filter_id!: () -> void

      def clear_filter_id_change: () -> void

      def filter_id_before_type_cast: () -> ::String

      def filter_id_for_database: () -> ::String

      def tag_id: () -> ::String

      def tag_id=: (::String) -> ::String

      def tag_id?: () -> bool

      def tag_id_changed?: () -> bool

      def tag_id_change: () -> [ ::String?, ::String? ]

      def tag_id_will_change!: () -> void

      def tag_id_was: () -> ::String?

      def tag_id_previously_changed?: () -> bool

      def tag_id_previous_change: () -> ::Array[::String?]?

      def tag_id_previously_was: () -> ::String?

      def tag_id_before_last_save: () -> ::String?

      def tag_id_change_to_be_saved: () -> ::Array[::String?]?

      def tag_id_in_database: () -> ::String?

      def saved_change_to_tag_id: () -> ::Array[::String?]?

      def saved_change_to_tag_id?: () -> bool

      def will_save_change_to_tag_id?: () -> bool

      def restore_tag_id!: () -> void

      def clear_tag_id_change: () -> void

      def tag_id_before_type_cast: () -> ::String

      def tag_id_for_database: () -> ::String
    end
    include ::Filter::HABTM_Tags::GeneratedAttributeMethods
    module ::Filter::HABTM_Tags::GeneratedAliasAttributeMethods
      include ::Filter::HABTM_Tags::GeneratedAttributeMethods
    end
    include ::Filter::HABTM_Tags::GeneratedAliasAttributeMethods

    def left_side: () -> ::Filter?
    def left_side=: (::Filter?) -> ::Filter?
    def reload_left_side: () -> ::Filter?
    def build_left_side: (untyped) -> ::Filter
    def create_left_side: (untyped) -> ::Filter
    def create_left_side!: (untyped) -> ::Filter
    def tag: () -> ::Tag?
    def tag=: (::Tag?) -> ::Tag?
    def reload_tag: () -> ::Tag?
    def build_tag: (untyped) -> ::Tag
    def create_tag: (untyped) -> ::Tag
    def create_tag!: (untyped) -> ::Tag
    module ::Filter::HABTM_Tags::GeneratedAssociationMethods
    end
    include ::Filter::HABTM_Tags::GeneratedAssociationMethods

    module ::Filter::HABTM_Tags::GeneratedRelationMethods
    end

    class ::Filter::HABTM_Tags::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Filter::HABTM_Tags]
      include ::Filter::HABTM_Tags::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Filter::HABTM_Tags, top]
    end

    class ::Filter::HABTM_Tags::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Filter::HABTM_Tags]
      include ::Filter::HABTM_Tags::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Filter::HABTM_Tags, top]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Filter::HABTM_Tags
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Filter::HABTM_Tags]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Filter::HABTM_Tags
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Filter::HABTM_Tags]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Filter::HABTM_Tags
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Filter::HABTM_Tags]
      def reload: () -> ::Array[::Filter::HABTM_Tags]

      def replace: (::Array[::Filter::HABTM_Tags]) -> void
      def delete: (*::Filter::HABTM_Tags | top) -> ::Array[::Filter::HABTM_Tags]
      def destroy: (*::Filter::HABTM_Tags | top) -> ::Array[::Filter::HABTM_Tags]
      def <<: (*::Filter::HABTM_Tags | ::Array[::Filter::HABTM_Tags]) -> self
      def prepend: (*::Filter::HABTM_Tags | ::Array[::Filter::HABTM_Tags]) -> self
    end
  end
end
