# resolve-type-names: false

class ::Filter < ::ApplicationRecord
  class ::Filter::HABTM_Assignees < ::ActiveRecord::Base
    extend ::ActiveRecord::Base::ClassMethods[::Filter::HABTM_Assignees, ::Filter::HABTM_Assignees::ActiveRecord_Relation, top]

    module ::Filter::HABTM_Assignees::GeneratedAttributeMethods
      def assignee_id: () -> ::String

      def assignee_id=: (::String) -> ::String

      def assignee_id?: () -> bool

      def assignee_id_changed?: () -> bool

      def assignee_id_change: () -> [ ::String?, ::String? ]

      def assignee_id_will_change!: () -> void

      def assignee_id_was: () -> ::String?

      def assignee_id_previously_changed?: () -> bool

      def assignee_id_previous_change: () -> ::Array[::String?]?

      def assignee_id_previously_was: () -> ::String?

      def assignee_id_before_last_save: () -> ::String?

      def assignee_id_change_to_be_saved: () -> ::Array[::String?]?

      def assignee_id_in_database: () -> ::String?

      def saved_change_to_assignee_id: () -> ::Array[::String?]?

      def saved_change_to_assignee_id?: () -> bool

      def will_save_change_to_assignee_id?: () -> bool

      def restore_assignee_id!: () -> void

      def clear_assignee_id_change: () -> void

      def assignee_id_before_type_cast: () -> ::String

      def assignee_id_for_database: () -> ::String

      def filter_id: () -> ::String

      def filter_id=: (::String) -> ::String

      def filter_id?: () -> bool

      def filter_id_changed?: () -> bool

      def filter_id_change: () -> [ ::String?, ::String? ]

      def filter_id_will_change!: () -> void

      def filter_id_was: () -> ::String?

      def filter_id_previously_changed?: () -> bool

      def filter_id_previous_change: () -> ::Array[::String?]?

      def filter_id_previously_was: () -> ::String?

      def filter_id_before_last_save: () -> ::String?

      def filter_id_change_to_be_saved: () -> ::Array[::String?]?

      def filter_id_in_database: () -> ::String?

      def saved_change_to_filter_id: () -> ::Array[::String?]?

      def saved_change_to_filter_id?: () -> bool

      def will_save_change_to_filter_id?: () -> bool

      def restore_filter_id!: () -> void

      def clear_filter_id_change: () -> void

      def filter_id_before_type_cast: () -> ::String

      def filter_id_for_database: () -> ::String
    end
    include ::Filter::HABTM_Assignees::GeneratedAttributeMethods
    module ::Filter::HABTM_Assignees::GeneratedAliasAttributeMethods
      include ::Filter::HABTM_Assignees::GeneratedAttributeMethods
    end
    include ::Filter::HABTM_Assignees::GeneratedAliasAttributeMethods

    def left_side: () -> ::Filter?
    def left_side=: (::Filter?) -> ::Filter?
    def reload_left_side: () -> ::Filter?
    def build_left_side: (untyped) -> ::Filter
    def create_left_side: (untyped) -> ::Filter
    def create_left_side!: (untyped) -> ::Filter
    def assignee: () -> ::User?
    def assignee=: (::User?) -> ::User?
    def reload_assignee: () -> ::User?
    def build_assignee: (untyped) -> ::User
    def create_assignee: (untyped) -> ::User
    def create_assignee!: (untyped) -> ::User
    module ::Filter::HABTM_Assignees::GeneratedAssociationMethods
    end
    include ::Filter::HABTM_Assignees::GeneratedAssociationMethods

    module ::Filter::HABTM_Assignees::GeneratedRelationMethods
    end

    class ::Filter::HABTM_Assignees::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Filter::HABTM_Assignees]
      include ::Filter::HABTM_Assignees::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Filter::HABTM_Assignees, top]
    end

    class ::Filter::HABTM_Assignees::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Filter::HABTM_Assignees]
      include ::Filter::HABTM_Assignees::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Filter::HABTM_Assignees, top]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Filter::HABTM_Assignees
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Filter::HABTM_Assignees]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Filter::HABTM_Assignees
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Filter::HABTM_Assignees]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Filter::HABTM_Assignees
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Filter::HABTM_Assignees]
      def reload: () -> ::Array[::Filter::HABTM_Assignees]

      def replace: (::Array[::Filter::HABTM_Assignees]) -> void
      def delete: (*::Filter::HABTM_Assignees | top) -> ::Array[::Filter::HABTM_Assignees]
      def destroy: (*::Filter::HABTM_Assignees | top) -> ::Array[::Filter::HABTM_Assignees]
      def <<: (*::Filter::HABTM_Assignees | ::Array[::Filter::HABTM_Assignees]) -> self
      def prepend: (*::Filter::HABTM_Assignees | ::Array[::Filter::HABTM_Assignees]) -> self
    end
  end
end
