# resolve-type-names: false

class ::Mention < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Mention, ::Mention::ActiveRecord_Relation, ::String]

  module ::Mention::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def mentionee_id: () -> ::String

    def mentionee_id=: (::String) -> ::String

    def mentionee_id?: () -> bool

    def mentionee_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def mentionee_id_change: () -> [ ::String?, ::String? ]

    def mentionee_id_will_change!: () -> void

    def mentionee_id_was: () -> ::String?

    def mentionee_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def mentionee_id_previous_change: () -> ::Array[::String?]?

    def mentionee_id_previously_was: () -> ::String?

    def mentionee_id_before_last_save: () -> ::String?

    def mentionee_id_change_to_be_saved: () -> ::Array[::String?]?

    def mentionee_id_in_database: () -> ::String?

    def saved_change_to_mentionee_id: () -> ::Array[::String?]?

    def saved_change_to_mentionee_id?: () -> bool

    def will_save_change_to_mentionee_id?: () -> bool

    def restore_mentionee_id!: () -> void

    def clear_mentionee_id_change: () -> void

    def mentionee_id_before_type_cast: () -> ::String

    def mentionee_id_for_database: () -> ::String

    def mentioner_id: () -> ::String

    def mentioner_id=: (::String) -> ::String

    def mentioner_id?: () -> bool

    def mentioner_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def mentioner_id_change: () -> [ ::String?, ::String? ]

    def mentioner_id_will_change!: () -> void

    def mentioner_id_was: () -> ::String?

    def mentioner_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def mentioner_id_previous_change: () -> ::Array[::String?]?

    def mentioner_id_previously_was: () -> ::String?

    def mentioner_id_before_last_save: () -> ::String?

    def mentioner_id_change_to_be_saved: () -> ::Array[::String?]?

    def mentioner_id_in_database: () -> ::String?

    def saved_change_to_mentioner_id: () -> ::Array[::String?]?

    def saved_change_to_mentioner_id?: () -> bool

    def will_save_change_to_mentioner_id?: () -> bool

    def restore_mentioner_id!: () -> void

    def clear_mentioner_id_change: () -> void

    def mentioner_id_before_type_cast: () -> ::String

    def mentioner_id_for_database: () -> ::String

    def source_id: () -> ::String

    def source_id=: (::String) -> ::String

    def source_id?: () -> bool

    def source_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def source_id_change: () -> [ ::String?, ::String? ]

    def source_id_will_change!: () -> void

    def source_id_was: () -> ::String?

    def source_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def source_id_previous_change: () -> ::Array[::String?]?

    def source_id_previously_was: () -> ::String?

    def source_id_before_last_save: () -> ::String?

    def source_id_change_to_be_saved: () -> ::Array[::String?]?

    def source_id_in_database: () -> ::String?

    def saved_change_to_source_id: () -> ::Array[::String?]?

    def saved_change_to_source_id?: () -> bool

    def will_save_change_to_source_id?: () -> bool

    def restore_source_id!: () -> void

    def clear_source_id_change: () -> void

    def source_id_before_type_cast: () -> ::String

    def source_id_for_database: () -> ::String

    def source_type: () -> ::String

    def source_type=: (::String) -> ::String

    def source_type?: () -> bool

    def source_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def source_type_change: () -> [ ::String?, ::String? ]

    def source_type_will_change!: () -> void

    def source_type_was: () -> ::String?

    def source_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def source_type_previous_change: () -> ::Array[::String?]?

    def source_type_previously_was: () -> ::String?

    def source_type_before_last_save: () -> ::String?

    def source_type_change_to_be_saved: () -> ::Array[::String?]?

    def source_type_in_database: () -> ::String?

    def saved_change_to_source_type: () -> ::Array[::String?]?

    def saved_change_to_source_type?: () -> bool

    def will_save_change_to_source_type?: () -> bool

    def restore_source_type!: () -> void

    def clear_source_type_change: () -> void

    def source_type_before_type_cast: () -> ::String

    def source_type_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def account_id: () -> ::String

    def account_id=: (::String) -> ::String

    def account_id?: () -> bool

    def account_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def account_id_change: () -> [ ::String?, ::String? ]

    def account_id_will_change!: () -> void

    def account_id_was: () -> ::String?

    def account_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def account_id_previous_change: () -> ::Array[::String?]?

    def account_id_previously_was: () -> ::String?

    def account_id_before_last_save: () -> ::String?

    def account_id_change_to_be_saved: () -> ::Array[::String?]?

    def account_id_in_database: () -> ::String?

    def saved_change_to_account_id: () -> ::Array[::String?]?

    def saved_change_to_account_id?: () -> bool

    def will_save_change_to_account_id?: () -> bool

    def restore_account_id!: () -> void

    def clear_account_id_change: () -> void

    def account_id_before_type_cast: () -> ::String

    def account_id_for_database: () -> ::String
  end
  include ::Mention::GeneratedAttributeMethods
  module ::Mention::GeneratedAliasAttributeMethods
    include ::Mention::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Mention::GeneratedAliasAttributeMethods
  def notifications: () -> ::Notification::ActiveRecord_Associations_CollectionProxy
  def notifications=: (::Notification::ActiveRecord_Associations_CollectionProxy | ::Array[::Notification]) -> (::Notification::ActiveRecord_Associations_CollectionProxy | ::Array[::Notification])
  def notification_ids: () -> ::Array[::Integer]
  def notification_ids=: (::Array[::Integer]) -> ::Array[::Integer]

  def account: () -> ::Account
  def account=: (::Account?) -> ::Account?
  def reload_account: () -> ::Account?
  def build_account: (untyped) -> ::Account
  def create_account: (untyped) -> ::Account
  def create_account!: (untyped) -> ::Account
  def source: () -> untyped
  def source=: (untyped?) -> untyped?
  def reload_source: () -> untyped?
  def mentioner: () -> ::User
  def mentioner=: (::User?) -> ::User?
  def reload_mentioner: () -> ::User?
  def build_mentioner: (untyped) -> ::User
  def create_mentioner: (untyped) -> ::User
  def create_mentioner!: (untyped) -> ::User
  def mentionee: () -> ::User
  def mentionee=: (::User?) -> ::User?
  def reload_mentionee: () -> ::User?
  def build_mentionee: (untyped) -> ::User
  def create_mentionee: (untyped) -> ::User
  def create_mentionee!: (untyped) -> ::User
  module ::Mention::GeneratedAssociationMethods
  end
  include ::Mention::GeneratedAssociationMethods

  module ::Mention::GeneratedRelationMethods
  end

  class ::Mention::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Mention]
    include ::Mention::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Mention, ::String]
  end

  class ::Mention::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Mention]
    include ::Mention::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Mention, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Mention
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Mention]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Mention
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Mention]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Mention
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Mention]
    def reload: () -> ::Array[::Mention]

    def replace: (::Array[::Mention]) -> void
    def delete: (*::Mention | ::String) -> ::Array[::Mention]
    def destroy: (*::Mention | ::String) -> ::Array[::Mention]
    def <<: (*::Mention | ::Array[::Mention]) -> self
    def prepend: (*::Mention | ::Array[::Mention]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Notification < ::ApplicationRecord
end
class ::Notification::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Account < ::ApplicationRecord
end
class ::User < ::ApplicationRecord
end
