---
name: actionview
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: d6e4d19ad6117272766c58412953cc5ec561a294
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
