---
name: actionview
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 57d3c396f6fcc458c0f26ad8153ad0e1ebffc567
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
