---
name: chunky_png
version: 1.4.0
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 551b26032ddffda787302eccf2106840d8ea7530
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
