---
name: minitest
version: '5.25'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 9892521a694a4cab3c179ae603b0111b87792919
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
