---
name: rake
version: '13.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: f7185de9d1309458e40995acfea0c4a930055eb2
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
