---
version: 1
callbacks:
- class: Account
  applies_self: Account & Account::Validated
  runs_before:
  - assign_external_account_id
  - create_join_code
- class: Account::JoinCode
  applies_self: Account::JoinCode & Account::JoinCode::Validated
  runs_before:
  - generate_code
- class: ActiveStorage::Blob
  applies_self: ActiveStorage::Blob & ActiveStorage::Blob::Validated
  runs_before:
  - touch_attachments
- class: Card
  applies_self: Card & Card::Validated
  runs_before:
  - set_default_title
  - assign_number
  - handle_board_change
  - track_board_change_event
- class: Notification
  applies_self: Notification & Notification::Validated
  runs_before:
  - bundle
- class: Reaction
  applies_self: Reaction & Reaction::Validated
  runs_before:
  - register_card_activity
- class: User::Settings
  applies_self: User::Settings & User::Settings::Validated
  runs_before:
  - review_pending_bundles
  - bundling_emails?
  - flush_pending_bundles
  - cancel_pending_bundles
- class: Webhook
  applies_self: Webhook & Webhook::Validated
  runs_before:
  - create_delinquency_tracker!
