# resolve-type-names: false

interface ::_RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> ::String
  def rails_info_properties_path: (*untyped) -> ::String
  def rails_info_routes_path: (*untyped) -> ::String
  def rails_info_notes_path: (*untyped) -> ::String
  def rails_info_path: (*untyped) -> ::String
  def root_path: (*untyped) -> ::String
  def account_cancellation_path: (*untyped) -> ::String
  def new_account_entropy_path: (*untyped) -> ::String
  def edit_account_entropy_path: (*untyped) -> ::String
  def account_entropy_path: (*untyped) -> ::String
  def new_account_join_code_path: (*untyped) -> ::String
  def edit_account_join_code_path: (*untyped) -> ::String
  def account_join_code_path: (*untyped) -> ::String
  def new_account_settings_path: (*untyped) -> ::String
  def edit_account_settings_path: (*untyped) -> ::String
  def account_settings_path: (*untyped) -> ::String
  def account_exports_path: (*untyped) -> ::String
  def account_export_path: (*untyped) -> ::String
  def account_imports_path: (*untyped) -> ::String
  def new_account_import_path: (*untyped) -> ::String
  def account_import_path: (*untyped) -> ::String
  def new_user_avatar_path: (*untyped) -> ::String
  def edit_user_avatar_path: (*untyped) -> ::String
  def user_avatar_path: (*untyped) -> ::String
  def new_user_role_path: (*untyped) -> ::String
  def edit_user_role_path: (*untyped) -> ::String
  def user_role_path: (*untyped) -> ::String
  def new_user_events_path: (*untyped) -> ::String
  def edit_user_events_path: (*untyped) -> ::String
  def user_events_path: (*untyped) -> ::String
  def user_push_subscriptions_path: (*untyped) -> ::String
  def new_user_push_subscription_path: (*untyped) -> ::String
  def edit_user_push_subscription_path: (*untyped) -> ::String
  def user_push_subscription_path: (*untyped) -> ::String
  def new_user_email_address_confirmation_path: (*untyped) -> ::String
  def edit_user_email_address_confirmation_path: (*untyped) -> ::String
  def user_email_address_confirmation_path: (*untyped) -> ::String
  def user_email_addresses_path: (*untyped) -> ::String
  def new_user_email_address_path: (*untyped) -> ::String
  def edit_user_email_address_path: (*untyped) -> ::String
  def user_email_address_path: (*untyped) -> ::String
  def user_data_exports_path: (*untyped) -> ::String
  def user_data_export_path: (*untyped) -> ::String
  def users_path: (*untyped) -> ::String
  def new_user_path: (*untyped) -> ::String
  def edit_user_path: (*untyped) -> ::String
  def user_path: (*untyped) -> ::String
  def new_board_subscriptions_path: (*untyped) -> ::String
  def edit_board_subscriptions_path: (*untyped) -> ::String
  def board_subscriptions_path: (*untyped) -> ::String
  def new_board_involvement_path: (*untyped) -> ::String
  def edit_board_involvement_path: (*untyped) -> ::String
  def board_involvement_path: (*untyped) -> ::String
  def new_board_publication_path: (*untyped) -> ::String
  def edit_board_publication_path: (*untyped) -> ::String
  def board_publication_path: (*untyped) -> ::String
  def new_board_entropy_path: (*untyped) -> ::String
  def edit_board_entropy_path: (*untyped) -> ::String
  def board_entropy_path: (*untyped) -> ::String
  def new_board_columns_not_now_path: (*untyped) -> ::String
  def edit_board_columns_not_now_path: (*untyped) -> ::String
  def board_columns_not_now_path: (*untyped) -> ::String
  def new_board_columns_stream_path: (*untyped) -> ::String
  def edit_board_columns_stream_path: (*untyped) -> ::String
  def board_columns_stream_path: (*untyped) -> ::String
  def new_board_columns_closed_path: (*untyped) -> ::String
  def edit_board_columns_closed_path: (*untyped) -> ::String
  def board_columns_closed_path: (*untyped) -> ::String
  def board_columns_path: (*untyped) -> ::String
  def new_board_column_path: (*untyped) -> ::String
  def edit_board_column_path: (*untyped) -> ::String
  def board_column_path: (*untyped) -> ::String
  def board_cards_path: (*untyped) -> ::String
  def board_webhook_activation_path: (*untyped) -> ::String
  def board_webhooks_path: (*untyped) -> ::String
  def new_board_webhook_path: (*untyped) -> ::String
  def edit_board_webhook_path: (*untyped) -> ::String
  def board_webhook_path: (*untyped) -> ::String
  def boards_path: (*untyped) -> ::String
  def new_board_path: (*untyped) -> ::String
  def edit_board_path: (*untyped) -> ::String
  def board_path: (*untyped) -> ::String
  def new_column_left_position_path: (*untyped) -> ::String
  def edit_column_left_position_path: (*untyped) -> ::String
  def column_left_position_path: (*untyped) -> ::String
  def new_column_right_position_path: (*untyped) -> ::String
  def edit_column_right_position_path: (*untyped) -> ::String
  def column_right_position_path: (*untyped) -> ::String
  def new_columns_card_drops_not_now_path: (*untyped) -> ::String
  def edit_columns_card_drops_not_now_path: (*untyped) -> ::String
  def columns_card_drops_not_now_path: (*untyped) -> ::String
  def new_columns_card_drops_stream_path: (*untyped) -> ::String
  def edit_columns_card_drops_stream_path: (*untyped) -> ::String
  def columns_card_drops_stream_path: (*untyped) -> ::String
  def new_columns_card_drops_closure_path: (*untyped) -> ::String
  def edit_columns_card_drops_closure_path: (*untyped) -> ::String
  def columns_card_drops_closure_path: (*untyped) -> ::String
  def new_columns_card_drops_column_path: (*untyped) -> ::String
  def edit_columns_card_drops_column_path: (*untyped) -> ::String
  def columns_card_drops_column_path: (*untyped) -> ::String
  def columns_cards_path: (*untyped) -> ::String
  def new_columns_card_path: (*untyped) -> ::String
  def edit_columns_card_path: (*untyped) -> ::String
  def columns_card_path: (*untyped) -> ::String
  def cards_previews_path: (*untyped) -> ::String
  def new_cards_preview_path: (*untyped) -> ::String
  def edit_cards_preview_path: (*untyped) -> ::String
  def cards_preview_path: (*untyped) -> ::String
  def card_draft_path: (*untyped) -> ::String
  def new_card_board_path: (*untyped) -> ::String
  def edit_card_board_path: (*untyped) -> ::String
  def card_board_path: (*untyped) -> ::String
  def new_card_closure_path: (*untyped) -> ::String
  def edit_card_closure_path: (*untyped) -> ::String
  def card_closure_path: (*untyped) -> ::String
  def new_card_column_path: (*untyped) -> ::String
  def edit_card_column_path: (*untyped) -> ::String
  def card_column_path: (*untyped) -> ::String
  def new_card_goldness_path: (*untyped) -> ::String
  def edit_card_goldness_path: (*untyped) -> ::String
  def card_goldness_path: (*untyped) -> ::String
  def new_card_image_path: (*untyped) -> ::String
  def edit_card_image_path: (*untyped) -> ::String
  def card_image_path: (*untyped) -> ::String
  def new_card_not_now_path: (*untyped) -> ::String
  def edit_card_not_now_path: (*untyped) -> ::String
  def card_not_now_path: (*untyped) -> ::String
  def new_card_pin_path: (*untyped) -> ::String
  def edit_card_pin_path: (*untyped) -> ::String
  def card_pin_path: (*untyped) -> ::String
  def new_card_publish_path: (*untyped) -> ::String
  def edit_card_publish_path: (*untyped) -> ::String
  def card_publish_path: (*untyped) -> ::String
  def new_card_reading_path: (*untyped) -> ::String
  def edit_card_reading_path: (*untyped) -> ::String
  def card_reading_path: (*untyped) -> ::String
  def new_card_triage_path: (*untyped) -> ::String
  def edit_card_triage_path: (*untyped) -> ::String
  def card_triage_path: (*untyped) -> ::String
  def new_card_watch_path: (*untyped) -> ::String
  def edit_card_watch_path: (*untyped) -> ::String
  def card_watch_path: (*untyped) -> ::String
  def card_reactions_path: (*untyped) -> ::String
  def new_card_reaction_path: (*untyped) -> ::String
  def edit_card_reaction_path: (*untyped) -> ::String
  def card_reaction_path: (*untyped) -> ::String
  def card_assignments_path: (*untyped) -> ::String
  def new_card_assignment_path: (*untyped) -> ::String
  def edit_card_assignment_path: (*untyped) -> ::String
  def card_assignment_path: (*untyped) -> ::String
  def card_self_assignment_path: (*untyped) -> ::String
  def card_steps_path: (*untyped) -> ::String
  def new_card_step_path: (*untyped) -> ::String
  def edit_card_step_path: (*untyped) -> ::String
  def card_step_path: (*untyped) -> ::String
  def card_taggings_path: (*untyped) -> ::String
  def new_card_tagging_path: (*untyped) -> ::String
  def edit_card_tagging_path: (*untyped) -> ::String
  def card_tagging_path: (*untyped) -> ::String
  def card_comment_reactions_path: (*untyped) -> ::String
  def new_card_comment_reaction_path: (*untyped) -> ::String
  def edit_card_comment_reaction_path: (*untyped) -> ::String
  def card_comment_reaction_path: (*untyped) -> ::String
  def card_comments_path: (*untyped) -> ::String
  def new_card_comment_path: (*untyped) -> ::String
  def edit_card_comment_path: (*untyped) -> ::String
  def card_comment_path: (*untyped) -> ::String
  def cards_path: (*untyped) -> ::String
  def new_card_path: (*untyped) -> ::String
  def edit_card_path: (*untyped) -> ::String
  def card_path: (*untyped) -> ::String
  def tags_path: (*untyped) -> ::String
  def new_notifications_settings_path: (*untyped) -> ::String
  def edit_notifications_settings_path: (*untyped) -> ::String
  def notifications_settings_path: (*untyped) -> ::String
  def new_notifications_unsubscribe_path: (*untyped) -> ::String
  def edit_notifications_unsubscribe_path: (*untyped) -> ::String
  def notifications_unsubscribe_path: (*untyped) -> ::String
  def tray_notifications_path: (*untyped) -> ::String
  def new_notification_reading_path: (*untyped) -> ::String
  def edit_notification_reading_path: (*untyped) -> ::String
  def notification_reading_path: (*untyped) -> ::String
  def bulk_reading_path: (*untyped) -> ::String
  def notifications_path: (*untyped) -> ::String
  def new_notification_path: (*untyped) -> ::String
  def edit_notification_path: (*untyped) -> ::String
  def notification_path: (*untyped) -> ::String
  def new_search_path: (*untyped) -> ::String
  def edit_search_path: (*untyped) -> ::String
  def search_path: (*untyped) -> ::String
  def searches_queries_path: (*untyped) -> ::String
  def new_searches_query_path: (*untyped) -> ::String
  def edit_searches_query_path: (*untyped) -> ::String
  def searches_query_path: (*untyped) -> ::String
  def settings_refresh_path: (*untyped) -> ::String
  def filters_path: (*untyped) -> ::String
  def new_filter_path: (*untyped) -> ::String
  def edit_filter_path: (*untyped) -> ::String
  def filter_path: (*untyped) -> ::String
  def events_path: (*untyped) -> ::String
  def events_days_path: (*untyped) -> ::String
  def new_events_day_path: (*untyped) -> ::String
  def edit_events_day_path: (*untyped) -> ::String
  def events_day_path: (*untyped) -> ::String
  def events_day_timeline_column_path: (*untyped) -> ::String
  def qr_codes_path: (*untyped) -> ::String
  def new_qr_code_path: (*untyped) -> ::String
  def edit_qr_code_path: (*untyped) -> ::String
  def qr_code_path: (*untyped) -> ::String
  def join_path: (*untyped) -> ::String
  def users_joins_path: (*untyped) -> ::String
  def new_users_join_path: (*untyped) -> ::String
  def edit_users_join_path: (*untyped) -> ::String
  def users_join_path: (*untyped) -> ::String
  def users_verifications_path: (*untyped) -> ::String
  def new_users_verification_path: (*untyped) -> ::String
  def session_transfers_path: (*untyped) -> ::String
  def new_session_transfer_path: (*untyped) -> ::String
  def edit_session_transfer_path: (*untyped) -> ::String
  def session_transfer_path: (*untyped) -> ::String
  def new_session_magic_link_path: (*untyped) -> ::String
  def edit_session_magic_link_path: (*untyped) -> ::String
  def session_magic_link_path: (*untyped) -> ::String
  def new_session_menu_path: (*untyped) -> ::String
  def edit_session_menu_path: (*untyped) -> ::String
  def session_menu_path: (*untyped) -> ::String
  def new_session_path: (*untyped) -> ::String
  def edit_session_path: (*untyped) -> ::String
  def session_path: (*untyped) -> ::String
  def signup_path: (*untyped) -> ::String
  def new_signup_completion_path: (*untyped) -> ::String
  def signup_completion_path: (*untyped) -> ::String
  def new_signup_path: (*untyped) -> ::String
  def new_landing_path: (*untyped) -> ::String
  def edit_landing_path: (*untyped) -> ::String
  def landing_path: (*untyped) -> ::String
  def my_identity_path: (*untyped) -> ::String
  def my_access_tokens_path: (*untyped) -> ::String
  def new_my_access_token_path: (*untyped) -> ::String
  def edit_my_access_token_path: (*untyped) -> ::String
  def my_access_token_path: (*untyped) -> ::String
  def my_pins_path: (*untyped) -> ::String
  def new_my_pin_path: (*untyped) -> ::String
  def edit_my_pin_path: (*untyped) -> ::String
  def my_pin_path: (*untyped) -> ::String
  def new_my_timezone_path: (*untyped) -> ::String
  def edit_my_timezone_path: (*untyped) -> ::String
  def my_timezone_path: (*untyped) -> ::String
  def new_my_menu_path: (*untyped) -> ::String
  def edit_my_menu_path: (*untyped) -> ::String
  def my_menu_path: (*untyped) -> ::String
  def prompts_cards_path: (*untyped) -> ::String
  def new_prompts_card_path: (*untyped) -> ::String
  def edit_prompts_card_path: (*untyped) -> ::String
  def prompts_card_path: (*untyped) -> ::String
  def prompts_tags_path: (*untyped) -> ::String
  def new_prompts_tag_path: (*untyped) -> ::String
  def edit_prompts_tag_path: (*untyped) -> ::String
  def prompts_tag_path: (*untyped) -> ::String
  def prompts_users_path: (*untyped) -> ::String
  def new_prompts_user_path: (*untyped) -> ::String
  def edit_prompts_user_path: (*untyped) -> ::String
  def prompts_user_path: (*untyped) -> ::String
  def prompts_board_users_path: (*untyped) -> ::String
  def new_prompts_board_user_path: (*untyped) -> ::String
  def edit_prompts_board_user_path: (*untyped) -> ::String
  def prompts_board_user_path: (*untyped) -> ::String
  def prompts_boards_path: (*untyped) -> ::String
  def new_prompts_board_path: (*untyped) -> ::String
  def edit_prompts_board_path: (*untyped) -> ::String
  def prompts_board_path: (*untyped) -> ::String
  def public_board_columns_not_now_path: (*untyped) -> ::String
  def public_board_columns_stream_path: (*untyped) -> ::String
  def public_board_columns_closed_path: (*untyped) -> ::String
  def public_board_column_path: (*untyped) -> ::String
  def public_board_card_path: (*untyped) -> ::String
  def public_boards_path: (*untyped) -> ::String
  def new_public_board_path: (*untyped) -> ::String
  def edit_public_board_path: (*untyped) -> ::String
  def public_board_path: (*untyped) -> ::String
  def published_board_path: (*untyped) -> ::String
  def published_card_path: (*untyped) -> ::String
  def rails_health_check_path: (*untyped) -> ::String
  def pwa_manifest_path: (*untyped) -> ::String
  def service_worker_path: (*untyped) -> ::String
  def admin_mission_control_jobs_path: (*untyped) -> ::String
  def turbo_recede_historical_location_path: (*untyped) -> ::String
  def turbo_resume_historical_location_path: (*untyped) -> ::String
  def turbo_refresh_historical_location_path: (*untyped) -> ::String
  def rails_postmark_inbound_emails_path: (*untyped) -> ::String
  def rails_relay_inbound_emails_path: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_path: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_path: (*untyped) -> ::String
  def rails_conductor_inbound_emails_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> ::String
  def rails_service_blob_path: (*untyped) -> ::String
  def rails_service_blob_proxy_path: (*untyped) -> ::String
  def rails_blob_representation_path: (*untyped) -> ::String
  def rails_blob_representation_proxy_path: (*untyped) -> ::String
  def rails_disk_service_path: (*untyped) -> ::String
  def update_rails_disk_service_path: (*untyped) -> ::String
  def rails_direct_uploads_path: (*untyped) -> ::String
  def rails_representation_path: (*untyped) -> ::String
  def rails_blob_path: (*untyped) -> ::String
  def rails_storage_proxy_path: (*untyped) -> ::String
  def rails_storage_redirect_path: (*untyped) -> ::String
  def rails_mailers_url: (*untyped) -> ::String
  def rails_info_properties_url: (*untyped) -> ::String
  def rails_info_routes_url: (*untyped) -> ::String
  def rails_info_notes_url: (*untyped) -> ::String
  def rails_info_url: (*untyped) -> ::String
  def root_url: (*untyped) -> ::String
  def account_cancellation_url: (*untyped) -> ::String
  def new_account_entropy_url: (*untyped) -> ::String
  def edit_account_entropy_url: (*untyped) -> ::String
  def account_entropy_url: (*untyped) -> ::String
  def new_account_join_code_url: (*untyped) -> ::String
  def edit_account_join_code_url: (*untyped) -> ::String
  def account_join_code_url: (*untyped) -> ::String
  def new_account_settings_url: (*untyped) -> ::String
  def edit_account_settings_url: (*untyped) -> ::String
  def account_settings_url: (*untyped) -> ::String
  def account_exports_url: (*untyped) -> ::String
  def account_export_url: (*untyped) -> ::String
  def account_imports_url: (*untyped) -> ::String
  def new_account_import_url: (*untyped) -> ::String
  def account_import_url: (*untyped) -> ::String
  def new_user_avatar_url: (*untyped) -> ::String
  def edit_user_avatar_url: (*untyped) -> ::String
  def user_avatar_url: (*untyped) -> ::String
  def new_user_role_url: (*untyped) -> ::String
  def edit_user_role_url: (*untyped) -> ::String
  def user_role_url: (*untyped) -> ::String
  def new_user_events_url: (*untyped) -> ::String
  def edit_user_events_url: (*untyped) -> ::String
  def user_events_url: (*untyped) -> ::String
  def user_push_subscriptions_url: (*untyped) -> ::String
  def new_user_push_subscription_url: (*untyped) -> ::String
  def edit_user_push_subscription_url: (*untyped) -> ::String
  def user_push_subscription_url: (*untyped) -> ::String
  def new_user_email_address_confirmation_url: (*untyped) -> ::String
  def edit_user_email_address_confirmation_url: (*untyped) -> ::String
  def user_email_address_confirmation_url: (*untyped) -> ::String
  def user_email_addresses_url: (*untyped) -> ::String
  def new_user_email_address_url: (*untyped) -> ::String
  def edit_user_email_address_url: (*untyped) -> ::String
  def user_email_address_url: (*untyped) -> ::String
  def user_data_exports_url: (*untyped) -> ::String
  def user_data_export_url: (*untyped) -> ::String
  def users_url: (*untyped) -> ::String
  def new_user_url: (*untyped) -> ::String
  def edit_user_url: (*untyped) -> ::String
  def user_url: (*untyped) -> ::String
  def new_board_subscriptions_url: (*untyped) -> ::String
  def edit_board_subscriptions_url: (*untyped) -> ::String
  def board_subscriptions_url: (*untyped) -> ::String
  def new_board_involvement_url: (*untyped) -> ::String
  def edit_board_involvement_url: (*untyped) -> ::String
  def board_involvement_url: (*untyped) -> ::String
  def new_board_publication_url: (*untyped) -> ::String
  def edit_board_publication_url: (*untyped) -> ::String
  def board_publication_url: (*untyped) -> ::String
  def new_board_entropy_url: (*untyped) -> ::String
  def edit_board_entropy_url: (*untyped) -> ::String
  def board_entropy_url: (*untyped) -> ::String
  def new_board_columns_not_now_url: (*untyped) -> ::String
  def edit_board_columns_not_now_url: (*untyped) -> ::String
  def board_columns_not_now_url: (*untyped) -> ::String
  def new_board_columns_stream_url: (*untyped) -> ::String
  def edit_board_columns_stream_url: (*untyped) -> ::String
  def board_columns_stream_url: (*untyped) -> ::String
  def new_board_columns_closed_url: (*untyped) -> ::String
  def edit_board_columns_closed_url: (*untyped) -> ::String
  def board_columns_closed_url: (*untyped) -> ::String
  def board_columns_url: (*untyped) -> ::String
  def new_board_column_url: (*untyped) -> ::String
  def edit_board_column_url: (*untyped) -> ::String
  def board_column_url: (*untyped) -> ::String
  def board_cards_url: (*untyped) -> ::String
  def board_webhook_activation_url: (*untyped) -> ::String
  def board_webhooks_url: (*untyped) -> ::String
  def new_board_webhook_url: (*untyped) -> ::String
  def edit_board_webhook_url: (*untyped) -> ::String
  def board_webhook_url: (*untyped) -> ::String
  def boards_url: (*untyped) -> ::String
  def new_board_url: (*untyped) -> ::String
  def edit_board_url: (*untyped) -> ::String
  def board_url: (*untyped) -> ::String
  def new_column_left_position_url: (*untyped) -> ::String
  def edit_column_left_position_url: (*untyped) -> ::String
  def column_left_position_url: (*untyped) -> ::String
  def new_column_right_position_url: (*untyped) -> ::String
  def edit_column_right_position_url: (*untyped) -> ::String
  def column_right_position_url: (*untyped) -> ::String
  def new_columns_card_drops_not_now_url: (*untyped) -> ::String
  def edit_columns_card_drops_not_now_url: (*untyped) -> ::String
  def columns_card_drops_not_now_url: (*untyped) -> ::String
  def new_columns_card_drops_stream_url: (*untyped) -> ::String
  def edit_columns_card_drops_stream_url: (*untyped) -> ::String
  def columns_card_drops_stream_url: (*untyped) -> ::String
  def new_columns_card_drops_closure_url: (*untyped) -> ::String
  def edit_columns_card_drops_closure_url: (*untyped) -> ::String
  def columns_card_drops_closure_url: (*untyped) -> ::String
  def new_columns_card_drops_column_url: (*untyped) -> ::String
  def edit_columns_card_drops_column_url: (*untyped) -> ::String
  def columns_card_drops_column_url: (*untyped) -> ::String
  def columns_cards_url: (*untyped) -> ::String
  def new_columns_card_url: (*untyped) -> ::String
  def edit_columns_card_url: (*untyped) -> ::String
  def columns_card_url: (*untyped) -> ::String
  def cards_previews_url: (*untyped) -> ::String
  def new_cards_preview_url: (*untyped) -> ::String
  def edit_cards_preview_url: (*untyped) -> ::String
  def cards_preview_url: (*untyped) -> ::String
  def card_draft_url: (*untyped) -> ::String
  def new_card_board_url: (*untyped) -> ::String
  def edit_card_board_url: (*untyped) -> ::String
  def card_board_url: (*untyped) -> ::String
  def new_card_closure_url: (*untyped) -> ::String
  def edit_card_closure_url: (*untyped) -> ::String
  def card_closure_url: (*untyped) -> ::String
  def new_card_column_url: (*untyped) -> ::String
  def edit_card_column_url: (*untyped) -> ::String
  def card_column_url: (*untyped) -> ::String
  def new_card_goldness_url: (*untyped) -> ::String
  def edit_card_goldness_url: (*untyped) -> ::String
  def card_goldness_url: (*untyped) -> ::String
  def new_card_image_url: (*untyped) -> ::String
  def edit_card_image_url: (*untyped) -> ::String
  def card_image_url: (*untyped) -> ::String
  def new_card_not_now_url: (*untyped) -> ::String
  def edit_card_not_now_url: (*untyped) -> ::String
  def card_not_now_url: (*untyped) -> ::String
  def new_card_pin_url: (*untyped) -> ::String
  def edit_card_pin_url: (*untyped) -> ::String
  def card_pin_url: (*untyped) -> ::String
  def new_card_publish_url: (*untyped) -> ::String
  def edit_card_publish_url: (*untyped) -> ::String
  def card_publish_url: (*untyped) -> ::String
  def new_card_reading_url: (*untyped) -> ::String
  def edit_card_reading_url: (*untyped) -> ::String
  def card_reading_url: (*untyped) -> ::String
  def new_card_triage_url: (*untyped) -> ::String
  def edit_card_triage_url: (*untyped) -> ::String
  def card_triage_url: (*untyped) -> ::String
  def new_card_watch_url: (*untyped) -> ::String
  def edit_card_watch_url: (*untyped) -> ::String
  def card_watch_url: (*untyped) -> ::String
  def card_reactions_url: (*untyped) -> ::String
  def new_card_reaction_url: (*untyped) -> ::String
  def edit_card_reaction_url: (*untyped) -> ::String
  def card_reaction_url: (*untyped) -> ::String
  def card_assignments_url: (*untyped) -> ::String
  def new_card_assignment_url: (*untyped) -> ::String
  def edit_card_assignment_url: (*untyped) -> ::String
  def card_assignment_url: (*untyped) -> ::String
  def card_self_assignment_url: (*untyped) -> ::String
  def card_steps_url: (*untyped) -> ::String
  def new_card_step_url: (*untyped) -> ::String
  def edit_card_step_url: (*untyped) -> ::String
  def card_step_url: (*untyped) -> ::String
  def card_taggings_url: (*untyped) -> ::String
  def new_card_tagging_url: (*untyped) -> ::String
  def edit_card_tagging_url: (*untyped) -> ::String
  def card_tagging_url: (*untyped) -> ::String
  def card_comment_reactions_url: (*untyped) -> ::String
  def new_card_comment_reaction_url: (*untyped) -> ::String
  def edit_card_comment_reaction_url: (*untyped) -> ::String
  def card_comment_reaction_url: (*untyped) -> ::String
  def card_comments_url: (*untyped) -> ::String
  def new_card_comment_url: (*untyped) -> ::String
  def edit_card_comment_url: (*untyped) -> ::String
  def card_comment_url: (*untyped) -> ::String
  def cards_url: (*untyped) -> ::String
  def new_card_url: (*untyped) -> ::String
  def edit_card_url: (*untyped) -> ::String
  def card_url: (*untyped) -> ::String
  def tags_url: (*untyped) -> ::String
  def new_notifications_settings_url: (*untyped) -> ::String
  def edit_notifications_settings_url: (*untyped) -> ::String
  def notifications_settings_url: (*untyped) -> ::String
  def new_notifications_unsubscribe_url: (*untyped) -> ::String
  def edit_notifications_unsubscribe_url: (*untyped) -> ::String
  def notifications_unsubscribe_url: (*untyped) -> ::String
  def tray_notifications_url: (*untyped) -> ::String
  def new_notification_reading_url: (*untyped) -> ::String
  def edit_notification_reading_url: (*untyped) -> ::String
  def notification_reading_url: (*untyped) -> ::String
  def bulk_reading_url: (*untyped) -> ::String
  def notifications_url: (*untyped) -> ::String
  def new_notification_url: (*untyped) -> ::String
  def edit_notification_url: (*untyped) -> ::String
  def notification_url: (*untyped) -> ::String
  def new_search_url: (*untyped) -> ::String
  def edit_search_url: (*untyped) -> ::String
  def search_url: (*untyped) -> ::String
  def searches_queries_url: (*untyped) -> ::String
  def new_searches_query_url: (*untyped) -> ::String
  def edit_searches_query_url: (*untyped) -> ::String
  def searches_query_url: (*untyped) -> ::String
  def settings_refresh_url: (*untyped) -> ::String
  def filters_url: (*untyped) -> ::String
  def new_filter_url: (*untyped) -> ::String
  def edit_filter_url: (*untyped) -> ::String
  def filter_url: (*untyped) -> ::String
  def events_url: (*untyped) -> ::String
  def events_days_url: (*untyped) -> ::String
  def new_events_day_url: (*untyped) -> ::String
  def edit_events_day_url: (*untyped) -> ::String
  def events_day_url: (*untyped) -> ::String
  def events_day_timeline_column_url: (*untyped) -> ::String
  def qr_codes_url: (*untyped) -> ::String
  def new_qr_code_url: (*untyped) -> ::String
  def edit_qr_code_url: (*untyped) -> ::String
  def qr_code_url: (*untyped) -> ::String
  def join_url: (*untyped) -> ::String
  def users_joins_url: (*untyped) -> ::String
  def new_users_join_url: (*untyped) -> ::String
  def edit_users_join_url: (*untyped) -> ::String
  def users_join_url: (*untyped) -> ::String
  def users_verifications_url: (*untyped) -> ::String
  def new_users_verification_url: (*untyped) -> ::String
  def session_transfers_url: (*untyped) -> ::String
  def new_session_transfer_url: (*untyped) -> ::String
  def edit_session_transfer_url: (*untyped) -> ::String
  def session_transfer_url: (*untyped) -> ::String
  def new_session_magic_link_url: (*untyped) -> ::String
  def edit_session_magic_link_url: (*untyped) -> ::String
  def session_magic_link_url: (*untyped) -> ::String
  def new_session_menu_url: (*untyped) -> ::String
  def edit_session_menu_url: (*untyped) -> ::String
  def session_menu_url: (*untyped) -> ::String
  def new_session_url: (*untyped) -> ::String
  def edit_session_url: (*untyped) -> ::String
  def session_url: (*untyped) -> ::String
  def signup_url: (*untyped) -> ::String
  def new_signup_completion_url: (*untyped) -> ::String
  def signup_completion_url: (*untyped) -> ::String
  def new_signup_url: (*untyped) -> ::String
  def new_landing_url: (*untyped) -> ::String
  def edit_landing_url: (*untyped) -> ::String
  def landing_url: (*untyped) -> ::String
  def my_identity_url: (*untyped) -> ::String
  def my_access_tokens_url: (*untyped) -> ::String
  def new_my_access_token_url: (*untyped) -> ::String
  def edit_my_access_token_url: (*untyped) -> ::String
  def my_access_token_url: (*untyped) -> ::String
  def my_pins_url: (*untyped) -> ::String
  def new_my_pin_url: (*untyped) -> ::String
  def edit_my_pin_url: (*untyped) -> ::String
  def my_pin_url: (*untyped) -> ::String
  def new_my_timezone_url: (*untyped) -> ::String
  def edit_my_timezone_url: (*untyped) -> ::String
  def my_timezone_url: (*untyped) -> ::String
  def new_my_menu_url: (*untyped) -> ::String
  def edit_my_menu_url: (*untyped) -> ::String
  def my_menu_url: (*untyped) -> ::String
  def prompts_cards_url: (*untyped) -> ::String
  def new_prompts_card_url: (*untyped) -> ::String
  def edit_prompts_card_url: (*untyped) -> ::String
  def prompts_card_url: (*untyped) -> ::String
  def prompts_tags_url: (*untyped) -> ::String
  def new_prompts_tag_url: (*untyped) -> ::String
  def edit_prompts_tag_url: (*untyped) -> ::String
  def prompts_tag_url: (*untyped) -> ::String
  def prompts_users_url: (*untyped) -> ::String
  def new_prompts_user_url: (*untyped) -> ::String
  def edit_prompts_user_url: (*untyped) -> ::String
  def prompts_user_url: (*untyped) -> ::String
  def prompts_board_users_url: (*untyped) -> ::String
  def new_prompts_board_user_url: (*untyped) -> ::String
  def edit_prompts_board_user_url: (*untyped) -> ::String
  def prompts_board_user_url: (*untyped) -> ::String
  def prompts_boards_url: (*untyped) -> ::String
  def new_prompts_board_url: (*untyped) -> ::String
  def edit_prompts_board_url: (*untyped) -> ::String
  def prompts_board_url: (*untyped) -> ::String
  def public_board_columns_not_now_url: (*untyped) -> ::String
  def public_board_columns_stream_url: (*untyped) -> ::String
  def public_board_columns_closed_url: (*untyped) -> ::String
  def public_board_column_url: (*untyped) -> ::String
  def public_board_card_url: (*untyped) -> ::String
  def public_boards_url: (*untyped) -> ::String
  def new_public_board_url: (*untyped) -> ::String
  def edit_public_board_url: (*untyped) -> ::String
  def public_board_url: (*untyped) -> ::String
  def published_board_url: (*untyped) -> ::String
  def published_card_url: (*untyped) -> ::String
  def rails_health_check_url: (*untyped) -> ::String
  def pwa_manifest_url: (*untyped) -> ::String
  def service_worker_url: (*untyped) -> ::String
  def admin_mission_control_jobs_url: (*untyped) -> ::String
  def turbo_recede_historical_location_url: (*untyped) -> ::String
  def turbo_resume_historical_location_url: (*untyped) -> ::String
  def turbo_refresh_historical_location_url: (*untyped) -> ::String
  def rails_postmark_inbound_emails_url: (*untyped) -> ::String
  def rails_relay_inbound_emails_url: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_url: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_url: (*untyped) -> ::String
  def rails_conductor_inbound_emails_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> ::String
  def rails_service_blob_url: (*untyped) -> ::String
  def rails_service_blob_proxy_url: (*untyped) -> ::String
  def rails_blob_representation_url: (*untyped) -> ::String
  def rails_blob_representation_proxy_url: (*untyped) -> ::String
  def rails_disk_service_url: (*untyped) -> ::String
  def update_rails_disk_service_url: (*untyped) -> ::String
  def rails_direct_uploads_url: (*untyped) -> ::String
  def rails_representation_url: (*untyped) -> ::String
  def rails_blob_url: (*untyped) -> ::String
  def rails_storage_proxy_url: (*untyped) -> ::String
  def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
  class ::ActionController::Base
    include ::_RbsRailsPathHelpers
  end
end
