# resolve-type-names: false

class ::Account < ::ApplicationRecord
  class ::Account::ExternalIdSequence < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Account::ExternalIdSequence, ::Account::ExternalIdSequence::ActiveRecord_Relation, ::String]

    module ::Account::ExternalIdSequence::GeneratedAttributeMethods
      def id: () -> ::String

      def id=: (::String) -> ::String

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ ::String?, ::String? ]

      def id_will_change!: () -> void

      def id_was: () -> ::String?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> ::Array[::String?]?

      def id_previously_was: () -> ::String?

      def id_before_last_save: () -> ::String?

      def id_change_to_be_saved: () -> ::Array[::String?]?

      def id_in_database: () -> ::String?

      def saved_change_to_id: () -> ::Array[::String?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::String

      def id_for_database: () -> ::String

      def value: () -> ::Integer

      def value=: (::Integer) -> ::Integer

      def value?: () -> bool

      def value_changed?: () -> bool

      def value_change: () -> [ ::Integer?, ::Integer? ]

      def value_will_change!: () -> void

      def value_was: () -> ::Integer?

      def value_previously_changed?: () -> bool

      def value_previous_change: () -> ::Array[::Integer?]?

      def value_previously_was: () -> ::Integer?

      def value_before_last_save: () -> ::Integer?

      def value_change_to_be_saved: () -> ::Array[::Integer?]?

      def value_in_database: () -> ::Integer?

      def saved_change_to_value: () -> ::Array[::Integer?]?

      def saved_change_to_value?: () -> bool

      def will_save_change_to_value?: () -> bool

      def restore_value!: () -> void

      def clear_value_change: () -> void

      def value_before_type_cast: () -> ::Integer

      def value_for_database: () -> ::Integer
    end
    include ::Account::ExternalIdSequence::GeneratedAttributeMethods
    module ::Account::ExternalIdSequence::GeneratedAliasAttributeMethods
      include ::Account::ExternalIdSequence::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Account::ExternalIdSequence::GeneratedAliasAttributeMethods

    module ::Account::ExternalIdSequence::GeneratedAssociationMethods
    end
    include ::Account::ExternalIdSequence::GeneratedAssociationMethods

    module ::Account::ExternalIdSequence::GeneratedRelationMethods
    end

    class ::Account::ExternalIdSequence::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Account::ExternalIdSequence]
      include ::Account::ExternalIdSequence::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Account::ExternalIdSequence, ::String]
    end

    class ::Account::ExternalIdSequence::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Account::ExternalIdSequence]
      include ::Account::ExternalIdSequence::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Account::ExternalIdSequence, ::String]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::ExternalIdSequence
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::ExternalIdSequence]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::ExternalIdSequence
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::ExternalIdSequence]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::ExternalIdSequence
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::ExternalIdSequence]
      def reload: () -> ::Array[::Account::ExternalIdSequence]

      def replace: (::Array[::Account::ExternalIdSequence]) -> void
      def delete: (*::Account::ExternalIdSequence | ::String) -> ::Array[::Account::ExternalIdSequence]
      def destroy: (*::Account::ExternalIdSequence | ::String) -> ::Array[::Account::ExternalIdSequence]
      def <<: (*::Account::ExternalIdSequence | ::Array[::Account::ExternalIdSequence]) -> self
      def prepend: (*::Account::ExternalIdSequence | ::Array[::Account::ExternalIdSequence]) -> self
    end
  end
end
