# resolve-type-names: false

class ::Account < ::ApplicationRecord
  class ::Account::Import < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Account::Import, ::Account::Import::ActiveRecord_Relation, ::String]

    module ::Account::Import::GeneratedAttributeMethods
      def id: () -> ::String

      def id=: (::String) -> ::String

      def id?: () -> bool

      def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def id_change: () -> [ ::String?, ::String? ]

      def id_will_change!: () -> void

      def id_was: () -> ::String?

      def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def id_previous_change: () -> ::Array[::String?]?

      def id_previously_was: () -> ::String?

      def id_before_last_save: () -> ::String?

      def id_change_to_be_saved: () -> ::Array[::String?]?

      def id_in_database: () -> ::String?

      def saved_change_to_id: () -> ::Array[::String?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::String

      def id_for_database: () -> ::String

      def identity_id: () -> ::String

      def identity_id=: (::String) -> ::String

      def identity_id?: () -> bool

      def identity_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def identity_id_change: () -> [ ::String?, ::String? ]

      def identity_id_will_change!: () -> void

      def identity_id_was: () -> ::String?

      def identity_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def identity_id_previous_change: () -> ::Array[::String?]?

      def identity_id_previously_was: () -> ::String?

      def identity_id_before_last_save: () -> ::String?

      def identity_id_change_to_be_saved: () -> ::Array[::String?]?

      def identity_id_in_database: () -> ::String?

      def saved_change_to_identity_id: () -> ::Array[::String?]?

      def saved_change_to_identity_id?: () -> bool

      def will_save_change_to_identity_id?: () -> bool

      def restore_identity_id!: () -> void

      def clear_identity_id_change: () -> void

      def identity_id_before_type_cast: () -> ::String

      def identity_id_for_database: () -> ::String

      def account_id: () -> ::String?

      def account_id=: (::String?) -> ::String?

      def account_id?: () -> bool

      def account_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_change: () -> [ ::String?, ::String? ]

      def account_id_will_change!: () -> void

      def account_id_was: () -> ::String?

      def account_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_previous_change: () -> ::Array[::String?]?

      def account_id_previously_was: () -> ::String?

      def account_id_before_last_save: () -> ::String?

      def account_id_change_to_be_saved: () -> ::Array[::String?]?

      def account_id_in_database: () -> ::String?

      def saved_change_to_account_id: () -> ::Array[::String?]?

      def saved_change_to_account_id?: () -> bool

      def will_save_change_to_account_id?: () -> bool

      def restore_account_id!: () -> void

      def clear_account_id_change: () -> void

      def account_id_before_type_cast: () -> ::String?

      def account_id_for_database: () -> ::String?

      def status: () -> ::String

      def status=: (::String) -> ::String

      def status?: () -> bool

      def status_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def status_change: () -> [ ::String?, ::String? ]

      def status_will_change!: () -> void

      def status_was: () -> ::String?

      def status_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def status_previous_change: () -> ::Array[::String?]?

      def status_previously_was: () -> ::String?

      def status_before_last_save: () -> ::String?

      def status_change_to_be_saved: () -> ::Array[::String?]?

      def status_in_database: () -> ::String?

      def saved_change_to_status: () -> ::Array[::String?]?

      def saved_change_to_status?: () -> bool

      def will_save_change_to_status?: () -> bool

      def restore_status!: () -> void

      def clear_status_change: () -> void

      def status_before_type_cast: () -> ::String

      def status_for_database: () -> ::String

      def completed_at: () -> ::ActiveSupport::TimeWithZone?

      def completed_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def completed_at?: () -> bool

      def completed_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def completed_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def completed_at_will_change!: () -> void

      def completed_at_was: () -> ::ActiveSupport::TimeWithZone?

      def completed_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def completed_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def completed_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def completed_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def completed_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def completed_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_completed_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_completed_at?: () -> bool

      def will_save_change_to_completed_at?: () -> bool

      def restore_completed_at!: () -> void

      def clear_completed_at_change: () -> void

      def completed_at_before_type_cast: () -> ::Time?

      def completed_at_for_database: () -> ::Time?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time

      def failure_reason: () -> ::String?

      def failure_reason=: (::String?) -> ::String?

      def failure_reason?: () -> bool

      def failure_reason_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def failure_reason_change: () -> [ ::String?, ::String? ]

      def failure_reason_will_change!: () -> void

      def failure_reason_was: () -> ::String?

      def failure_reason_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def failure_reason_previous_change: () -> ::Array[::String?]?

      def failure_reason_previously_was: () -> ::String?

      def failure_reason_before_last_save: () -> ::String?

      def failure_reason_change_to_be_saved: () -> ::Array[::String?]?

      def failure_reason_in_database: () -> ::String?

      def saved_change_to_failure_reason: () -> ::Array[::String?]?

      def saved_change_to_failure_reason?: () -> bool

      def will_save_change_to_failure_reason?: () -> bool

      def restore_failure_reason!: () -> void

      def clear_failure_reason_change: () -> void

      def failure_reason_before_type_cast: () -> ::String?

      def failure_reason_for_database: () -> ::String?
    end
    include ::Account::Import::GeneratedAttributeMethods
    module ::Account::Import::GeneratedAliasAttributeMethods
      include ::Account::Import::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Account::Import::GeneratedAliasAttributeMethods

    def file_attachment: () -> ::ActiveStorage::Attachment?
    def file_attachment=: (::ActiveStorage::Attachment?) -> ::ActiveStorage::Attachment?
    def build_file_attachment: (?untyped) -> ::ActiveStorage::Attachment
    def create_file_attachment: (?untyped) -> ::ActiveStorage::Attachment
    def create_file_attachment!: (?untyped) -> ::ActiveStorage::Attachment
    def reload_file_attachment: () -> ::ActiveStorage::Attachment?
    def file_blob: () -> ::ActiveStorage::Blob?
    def file_blob=: (::ActiveStorage::Blob?) -> ::ActiveStorage::Blob?
    def build_file_blob: (?untyped) -> ::ActiveStorage::Blob
    def create_file_blob: (?untyped) -> ::ActiveStorage::Blob
    def create_file_blob!: (?untyped) -> ::ActiveStorage::Blob
    def reload_file_blob: () -> ::ActiveStorage::Blob?
    def account: () -> ::Account
    def account=: (::Account?) -> ::Account?
    def reload_account: () -> ::Account?
    def build_account: (untyped) -> ::Account
    def create_account: (untyped) -> ::Account
    def create_account!: (untyped) -> ::Account
    def identity: () -> ::Identity
    def identity=: (::Identity?) -> ::Identity?
    def reload_identity: () -> ::Identity?
    def build_identity: (untyped) -> ::Identity
    def create_identity: (untyped) -> ::Identity
    def create_identity!: (untyped) -> ::Identity
    module ::Account::Import::GeneratedAssociationMethods
      def file: () -> ::ActiveStorage::Attached::One

      def file=: (::ActionDispatch::Http::UploadedFile) -> ::ActionDispatch::Http::UploadedFile
               | (::Rack::Test::UploadedFile) -> ::Rack::Test::UploadedFile
               | (::ActiveStorage::Blob) -> ::ActiveStorage::Blob
               | (::String) -> ::String
               | ({ io: ::IO, filename: ::String, content_type: ::String? }) -> { io: ::IO, filename: ::String, content_type: ::String? }
               | (nil) -> nil
    end
    include ::Account::Import::GeneratedAssociationMethods

    def pending!: () -> bool
    def pending?: () -> bool
    def processing!: () -> bool
    def processing?: () -> bool
    def completed!: () -> bool
    def completed?: () -> bool
    def failed!: () -> bool
    def failed?: () -> bool
    def failed_due_to_conflict!: () -> bool
    def failed_due_to_conflict?: () -> bool
    def failed_due_to_invalid_export!: () -> bool
    def failed_due_to_invalid_export?: () -> bool
    def self.statuses: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
    def self.failure_reasons: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
    def self.pending: () -> ::Account::Import::ActiveRecord_Relation
    def self.not_pending: () -> ::Account::Import::ActiveRecord_Relation
    def self.processing: () -> ::Account::Import::ActiveRecord_Relation
    def self.not_processing: () -> ::Account::Import::ActiveRecord_Relation
    def self.completed: () -> ::Account::Import::ActiveRecord_Relation
    def self.not_completed: () -> ::Account::Import::ActiveRecord_Relation
    def self.failed: () -> ::Account::Import::ActiveRecord_Relation
    def self.not_failed: () -> ::Account::Import::ActiveRecord_Relation
    def self.failed_due_to_conflict: () -> ::Account::Import::ActiveRecord_Relation
    def self.not_failed_due_to_conflict: () -> ::Account::Import::ActiveRecord_Relation
    def self.failed_due_to_invalid_export: () -> ::Account::Import::ActiveRecord_Relation
    def self.not_failed_due_to_invalid_export: () -> ::Account::Import::ActiveRecord_Relation
    def self.with_attached_file: () -> ::Account::Import::ActiveRecord_Relation
    def self.expired: () -> ::Account::Import::ActiveRecord_Relation

    module ::Account::Import::GeneratedRelationMethods
      def statuses: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

      def failure_reasons: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

      def pending: () -> ::Account::Import::ActiveRecord_Relation

      def not_pending: () -> ::Account::Import::ActiveRecord_Relation

      def processing: () -> ::Account::Import::ActiveRecord_Relation

      def not_processing: () -> ::Account::Import::ActiveRecord_Relation

      def completed: () -> ::Account::Import::ActiveRecord_Relation

      def not_completed: () -> ::Account::Import::ActiveRecord_Relation

      def failed: () -> ::Account::Import::ActiveRecord_Relation

      def not_failed: () -> ::Account::Import::ActiveRecord_Relation

      def failed_due_to_conflict: () -> ::Account::Import::ActiveRecord_Relation

      def not_failed_due_to_conflict: () -> ::Account::Import::ActiveRecord_Relation

      def failed_due_to_invalid_export: () -> ::Account::Import::ActiveRecord_Relation

      def not_failed_due_to_invalid_export: () -> ::Account::Import::ActiveRecord_Relation

      def with_attached_file: () -> ::Account::Import::ActiveRecord_Relation

      def expired: () -> ::Account::Import::ActiveRecord_Relation
    end

    class ::Account::Import::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Account::Import]
      include ::Account::Import::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Account::Import, ::String]
    end

    class ::Account::Import::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Account::Import]
      include ::Account::Import::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Account::Import, ::String]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::Import
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::Import]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::Import
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::Import]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::Import
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::Import]
      def reload: () -> ::Array[::Account::Import]

      def replace: (::Array[::Account::Import]) -> void
      def delete: (*::Account::Import | ::String) -> ::Array[::Account::Import]
      def destroy: (*::Account::Import | ::String) -> ::Array[::Account::Import]
      def <<: (*::Account::Import | ::Array[::Account::Import]) -> self
      def prepend: (*::Account::Import | ::Array[::Account::Import]) -> self
    end
  end
end

class ::Account < ::ApplicationRecord
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Identity < ::ApplicationRecord
end
