# resolve-type-names: false

class ::Account < ::ApplicationRecord
  class ::Account::JoinCode < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Account::JoinCode, ::Account::JoinCode::ActiveRecord_Relation, ::String]

    module ::Account::JoinCode::GeneratedAttributeMethods
      def id: () -> ::String

      def id=: (::String) -> ::String

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ ::String?, ::String? ]

      def id_will_change!: () -> void

      def id_was: () -> ::String?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> ::Array[::String?]?

      def id_previously_was: () -> ::String?

      def id_before_last_save: () -> ::String?

      def id_change_to_be_saved: () -> ::Array[::String?]?

      def id_in_database: () -> ::String?

      def saved_change_to_id: () -> ::Array[::String?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::String

      def id_for_database: () -> ::String

      def account_id: () -> ::String

      def account_id=: (::String) -> ::String

      def account_id?: () -> bool

      def account_id_changed?: () -> bool

      def account_id_change: () -> [ ::String?, ::String? ]

      def account_id_will_change!: () -> void

      def account_id_was: () -> ::String?

      def account_id_previously_changed?: () -> bool

      def account_id_previous_change: () -> ::Array[::String?]?

      def account_id_previously_was: () -> ::String?

      def account_id_before_last_save: () -> ::String?

      def account_id_change_to_be_saved: () -> ::Array[::String?]?

      def account_id_in_database: () -> ::String?

      def saved_change_to_account_id: () -> ::Array[::String?]?

      def saved_change_to_account_id?: () -> bool

      def will_save_change_to_account_id?: () -> bool

      def restore_account_id!: () -> void

      def clear_account_id_change: () -> void

      def account_id_before_type_cast: () -> ::String

      def account_id_for_database: () -> ::String

      def code: () -> ::String

      def code=: (::String) -> ::String

      def code?: () -> bool

      def code_changed?: () -> bool

      def code_change: () -> [ ::String?, ::String? ]

      def code_will_change!: () -> void

      def code_was: () -> ::String?

      def code_previously_changed?: () -> bool

      def code_previous_change: () -> ::Array[::String?]?

      def code_previously_was: () -> ::String?

      def code_before_last_save: () -> ::String?

      def code_change_to_be_saved: () -> ::Array[::String?]?

      def code_in_database: () -> ::String?

      def saved_change_to_code: () -> ::Array[::String?]?

      def saved_change_to_code?: () -> bool

      def will_save_change_to_code?: () -> bool

      def restore_code!: () -> void

      def clear_code_change: () -> void

      def code_before_type_cast: () -> ::String

      def code_for_database: () -> ::String

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: () -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: () -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: () -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: () -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time

      def usage_count: () -> ::Integer

      def usage_count=: (::Integer) -> ::Integer

      def usage_count?: () -> bool

      def usage_count_changed?: () -> bool

      def usage_count_change: () -> [ ::Integer?, ::Integer? ]

      def usage_count_will_change!: () -> void

      def usage_count_was: () -> ::Integer?

      def usage_count_previously_changed?: () -> bool

      def usage_count_previous_change: () -> ::Array[::Integer?]?

      def usage_count_previously_was: () -> ::Integer?

      def usage_count_before_last_save: () -> ::Integer?

      def usage_count_change_to_be_saved: () -> ::Array[::Integer?]?

      def usage_count_in_database: () -> ::Integer?

      def saved_change_to_usage_count: () -> ::Array[::Integer?]?

      def saved_change_to_usage_count?: () -> bool

      def will_save_change_to_usage_count?: () -> bool

      def restore_usage_count!: () -> void

      def clear_usage_count_change: () -> void

      def usage_count_before_type_cast: () -> ::Integer

      def usage_count_for_database: () -> ::Integer

      def usage_limit: () -> ::Integer

      def usage_limit=: (::Integer) -> ::Integer

      def usage_limit?: () -> bool

      def usage_limit_changed?: () -> bool

      def usage_limit_change: () -> [ ::Integer?, ::Integer? ]

      def usage_limit_will_change!: () -> void

      def usage_limit_was: () -> ::Integer?

      def usage_limit_previously_changed?: () -> bool

      def usage_limit_previous_change: () -> ::Array[::Integer?]?

      def usage_limit_previously_was: () -> ::Integer?

      def usage_limit_before_last_save: () -> ::Integer?

      def usage_limit_change_to_be_saved: () -> ::Array[::Integer?]?

      def usage_limit_in_database: () -> ::Integer?

      def saved_change_to_usage_limit: () -> ::Array[::Integer?]?

      def saved_change_to_usage_limit?: () -> bool

      def will_save_change_to_usage_limit?: () -> bool

      def restore_usage_limit!: () -> void

      def clear_usage_limit_change: () -> void

      def usage_limit_before_type_cast: () -> ::Integer

      def usage_limit_for_database: () -> ::Integer
    end
    include ::Account::JoinCode::GeneratedAttributeMethods
    module ::Account::JoinCode::GeneratedAliasAttributeMethods
      include ::Account::JoinCode::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Account::JoinCode::GeneratedAliasAttributeMethods

    def account: () -> ::Account
    def account=: (::Account?) -> ::Account?
    def reload_account: () -> ::Account?
    def build_account: (untyped) -> ::Account
    def create_account: (untyped) -> ::Account
    def create_account!: (untyped) -> ::Account
    module ::Account::JoinCode::GeneratedAssociationMethods
    end
    include ::Account::JoinCode::GeneratedAssociationMethods

    def self.active: () -> ::Account::JoinCode::ActiveRecord_Relation

    module ::Account::JoinCode::GeneratedRelationMethods
      def active: () -> ::Account::JoinCode::ActiveRecord_Relation
    end

    class ::Account::JoinCode::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Account::JoinCode]
      include ::Account::JoinCode::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Account::JoinCode, ::String]
    end

    class ::Account::JoinCode::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Account::JoinCode]
      include ::Account::JoinCode::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Account::JoinCode, ::String]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::JoinCode
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::JoinCode]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::JoinCode
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::JoinCode]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Account::JoinCode
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Account::JoinCode]
      def reload: () -> ::Array[::Account::JoinCode]

      def replace: (::Array[::Account::JoinCode]) -> void
      def delete: (*::Account::JoinCode | ::String) -> ::Array[::Account::JoinCode]
      def destroy: (*::Account::JoinCode | ::String) -> ::Array[::Account::JoinCode]
      def <<: (*::Account::JoinCode | ::Array[::Account::JoinCode]) -> self
      def prepend: (*::Account::JoinCode | ::Array[::Account::JoinCode]) -> self
    end
  end
end
