# resolve-type-names: false

module ::ActionText
  class ::ActionText::RichText < ::ActionText::Record
    extend ::ActiveRecord::Base::ClassMethods[::ActionText::RichText, ::ActionText::RichText::ActiveRecord_Relation, ::String]

    module ::ActionText::RichText::GeneratedAttributeMethods
      def id: () -> ::String

      def id=: (::String) -> ::String

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ ::String?, ::String? ]

      def id_will_change!: () -> void

      def id_was: () -> ::String?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> ::Array[::String?]?

      def id_previously_was: () -> ::String?

      def id_before_last_save: () -> ::String?

      def id_change_to_be_saved: () -> ::Array[::String?]?

      def id_in_database: () -> ::String?

      def saved_change_to_id: () -> ::Array[::String?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::String

      def id_for_database: () -> ::String

      def body: () -> ::String?

      def body=: (::String?) -> ::String?

      def body?: () -> bool

      def body_changed?: () -> bool

      def body_change: () -> [ ::String?, ::String? ]

      def body_will_change!: () -> void

      def body_was: () -> ::String?

      def body_previously_changed?: () -> bool

      def body_previous_change: () -> ::Array[::String?]?

      def body_previously_was: () -> ::String?

      def body_before_last_save: () -> ::String?

      def body_change_to_be_saved: () -> ::Array[::String?]?

      def body_in_database: () -> ::String?

      def saved_change_to_body: () -> ::Array[::String?]?

      def saved_change_to_body?: () -> bool

      def will_save_change_to_body?: () -> bool

      def restore_body!: () -> void

      def clear_body_change: () -> void

      def body_before_type_cast: () -> ::String?

      def body_for_database: () -> ::String?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: () -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: () -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def name: () -> ::String

      def name=: (::String) -> ::String

      def name?: () -> bool

      def name_changed?: () -> bool

      def name_change: () -> [ ::String?, ::String? ]

      def name_will_change!: () -> void

      def name_was: () -> ::String?

      def name_previously_changed?: () -> bool

      def name_previous_change: () -> ::Array[::String?]?

      def name_previously_was: () -> ::String?

      def name_before_last_save: () -> ::String?

      def name_change_to_be_saved: () -> ::Array[::String?]?

      def name_in_database: () -> ::String?

      def saved_change_to_name: () -> ::Array[::String?]?

      def saved_change_to_name?: () -> bool

      def will_save_change_to_name?: () -> bool

      def restore_name!: () -> void

      def clear_name_change: () -> void

      def name_before_type_cast: () -> ::String

      def name_for_database: () -> ::String

      def record_id: () -> ::String

      def record_id=: (::String) -> ::String

      def record_id?: () -> bool

      def record_id_changed?: () -> bool

      def record_id_change: () -> [ ::String?, ::String? ]

      def record_id_will_change!: () -> void

      def record_id_was: () -> ::String?

      def record_id_previously_changed?: () -> bool

      def record_id_previous_change: () -> ::Array[::String?]?

      def record_id_previously_was: () -> ::String?

      def record_id_before_last_save: () -> ::String?

      def record_id_change_to_be_saved: () -> ::Array[::String?]?

      def record_id_in_database: () -> ::String?

      def saved_change_to_record_id: () -> ::Array[::String?]?

      def saved_change_to_record_id?: () -> bool

      def will_save_change_to_record_id?: () -> bool

      def restore_record_id!: () -> void

      def clear_record_id_change: () -> void

      def record_id_before_type_cast: () -> ::String

      def record_id_for_database: () -> ::String

      def record_type: () -> ::String

      def record_type=: (::String) -> ::String

      def record_type?: () -> bool

      def record_type_changed?: () -> bool

      def record_type_change: () -> [ ::String?, ::String? ]

      def record_type_will_change!: () -> void

      def record_type_was: () -> ::String?

      def record_type_previously_changed?: () -> bool

      def record_type_previous_change: () -> ::Array[::String?]?

      def record_type_previously_was: () -> ::String?

      def record_type_before_last_save: () -> ::String?

      def record_type_change_to_be_saved: () -> ::Array[::String?]?

      def record_type_in_database: () -> ::String?

      def saved_change_to_record_type: () -> ::Array[::String?]?

      def saved_change_to_record_type?: () -> bool

      def will_save_change_to_record_type?: () -> bool

      def restore_record_type!: () -> void

      def clear_record_type_change: () -> void

      def record_type_before_type_cast: () -> ::String

      def record_type_for_database: () -> ::String

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: () -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: () -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time

      def account_id: () -> ::String

      def account_id=: (::String) -> ::String

      def account_id?: () -> bool

      def account_id_changed?: () -> bool

      def account_id_change: () -> [ ::String?, ::String? ]

      def account_id_will_change!: () -> void

      def account_id_was: () -> ::String?

      def account_id_previously_changed?: () -> bool

      def account_id_previous_change: () -> ::Array[::String?]?

      def account_id_previously_was: () -> ::String?

      def account_id_before_last_save: () -> ::String?

      def account_id_change_to_be_saved: () -> ::Array[::String?]?

      def account_id_in_database: () -> ::String?

      def saved_change_to_account_id: () -> ::Array[::String?]?

      def saved_change_to_account_id?: () -> bool

      def will_save_change_to_account_id?: () -> bool

      def restore_account_id!: () -> void

      def clear_account_id_change: () -> void

      def account_id_before_type_cast: () -> ::String

      def account_id_for_database: () -> ::String
    end
    include ::ActionText::RichText::GeneratedAttributeMethods
    module ::ActionText::RichText::GeneratedAliasAttributeMethods
      include ::ActionText::RichText::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::ActionText::RichText::GeneratedAliasAttributeMethods
    def embeds_attachments: () -> ::ActiveStorage::Attachment::ActiveRecord_Associations_CollectionProxy
    def embeds_attachments=: (::ActiveStorage::Attachment::ActiveRecord_Associations_CollectionProxy | ::Array[::ActiveStorage::Attachment]) -> (::ActiveStorage::Attachment::ActiveRecord_Associations_CollectionProxy | ::Array[::ActiveStorage::Attachment])
    def embeds_attachment_ids: () -> ::Array[::Integer]
    def embeds_attachment_ids=: (::Array[::Integer]) -> ::Array[::Integer]
    def embeds_blobs: () -> ::ActiveStorage::Blob::ActiveRecord_Associations_CollectionProxy
    def embeds_blobs=: (::ActiveStorage::Blob::ActiveRecord_Associations_CollectionProxy | ::Array[::ActiveStorage::Blob]) -> (::ActiveStorage::Blob::ActiveRecord_Associations_CollectionProxy | ::Array[::ActiveStorage::Blob])
    def embeds_blob_ids: () -> ::Array[::Integer]
    def embeds_blob_ids=: (::Array[::Integer]) -> ::Array[::Integer]

    def record: () -> untyped
    def record=: (untyped?) -> untyped?
    def reload_record: () -> untyped?
    def account: () -> ::Account
    def account=: (::Account?) -> ::Account?
    def reload_account: () -> ::Account?
    def build_account: (untyped) -> ::Account
    def create_account: (untyped) -> ::Account
    def create_account!: (untyped) -> ::Account
    module ::ActionText::RichText::GeneratedAssociationMethods
      def embeds: () -> ::ActiveStorage::Attached::Many

      def embeds=: (untyped) -> untyped
    end
    include ::ActionText::RichText::GeneratedAssociationMethods

    def self.with_attached_embeds: () -> ::ActionText::RichText::ActiveRecord_Relation

    module ::ActionText::RichText::GeneratedRelationMethods
      def with_attached_embeds: () -> ::ActionText::RichText::ActiveRecord_Relation
    end

    class ::ActionText::RichText::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::ActionText::RichText]
      include ::ActionText::RichText::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::ActionText::RichText, ::String]
    end

    class ::ActionText::RichText::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::ActionText::RichText]
      include ::ActionText::RichText::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::ActionText::RichText, ::String]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ActionText::RichText
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ActionText::RichText]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ActionText::RichText
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ActionText::RichText]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ActionText::RichText
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ActionText::RichText]
      def reload: () -> ::Array[::ActionText::RichText]

      def replace: (::Array[::ActionText::RichText]) -> void
      def delete: (*::ActionText::RichText | ::String) -> ::Array[::ActionText::RichText]
      def destroy: (*::ActionText::RichText | ::String) -> ::Array[::ActionText::RichText]
      def <<: (*::ActionText::RichText | ::Array[::ActionText::RichText]) -> self
      def prepend: (*::ActionText::RichText | ::Array[::ActionText::RichText]) -> self
    end
  end
end
