---
name: activerecord
version: '8.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 870e3ef8521e330af8dad256ecb66030b649ef3a
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
