---
name: net-smtp
version: '0.5'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 31840bef3fae6dd337a2db2a67116f15cbc37ce6
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
