---
name: logger
version: '1.7'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 33157eca101c8babe9928ccb61bd0376c0005d52
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
