# resolve-type-names: false

module ::SolidCache
  class ::SolidCache::Entry < ::SolidCache::Record
    extend ::ActiveRecord::Base::ClassMethods[::SolidCache::Entry, ::SolidCache::Entry::ActiveRecord_Relation, ::Integer, ::SolidCache::Entry::Validated]

    module ::SolidCache::Entry::GeneratedAttributeMethods
      def id: () -> ::Integer?

      def id=: (::Integer?) -> ::Integer?

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer?

      def id_for_database: () -> ::Integer?

      def byte_size: () -> ::Integer?

      def byte_size=: (::Integer?) -> ::Integer?

      def byte_size?: () -> bool

      def byte_size_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def byte_size_change: () -> [ ::Integer?, ::Integer? ]

      def byte_size_will_change!: () -> void

      def byte_size_was: () -> ::Integer?

      def byte_size_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def byte_size_previous_change: () -> ::Array[::Integer?]?

      def byte_size_previously_was: () -> ::Integer?

      def byte_size_before_last_save: () -> ::Integer?

      def byte_size_change_to_be_saved: () -> ::Array[::Integer?]?

      def byte_size_in_database: () -> ::Integer?

      def saved_change_to_byte_size: () -> ::Array[::Integer?]?

      def saved_change_to_byte_size?: () -> bool

      def will_save_change_to_byte_size?: () -> bool

      def restore_byte_size!: () -> void

      def clear_byte_size_change: () -> void

      def byte_size_before_type_cast: () -> ::Integer?

      def byte_size_for_database: () -> ::Integer?

      def created_at: () -> ::ActiveSupport::TimeWithZone?

      def created_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time?

      def created_at_for_database: () -> ::Time?

      def key: () -> ::String?

      def key=: (::String?) -> ::String?

      def key?: () -> bool

      def key_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def key_change: () -> [ ::String?, ::String? ]

      def key_will_change!: () -> void

      def key_was: () -> ::String?

      def key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def key_previous_change: () -> ::Array[::String?]?

      def key_previously_was: () -> ::String?

      def key_before_last_save: () -> ::String?

      def key_change_to_be_saved: () -> ::Array[::String?]?

      def key_in_database: () -> ::String?

      def saved_change_to_key: () -> ::Array[::String?]?

      def saved_change_to_key?: () -> bool

      def will_save_change_to_key?: () -> bool

      def restore_key!: () -> void

      def clear_key_change: () -> void

      def key_before_type_cast: () -> ::String?

      def key_for_database: () -> ::String?

      def key_hash: () -> ::Integer?

      def key_hash=: (::Integer?) -> ::Integer?

      def key_hash?: () -> bool

      def key_hash_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def key_hash_change: () -> [ ::Integer?, ::Integer? ]

      def key_hash_will_change!: () -> void

      def key_hash_was: () -> ::Integer?

      def key_hash_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def key_hash_previous_change: () -> ::Array[::Integer?]?

      def key_hash_previously_was: () -> ::Integer?

      def key_hash_before_last_save: () -> ::Integer?

      def key_hash_change_to_be_saved: () -> ::Array[::Integer?]?

      def key_hash_in_database: () -> ::Integer?

      def saved_change_to_key_hash: () -> ::Array[::Integer?]?

      def saved_change_to_key_hash?: () -> bool

      def will_save_change_to_key_hash?: () -> bool

      def restore_key_hash!: () -> void

      def clear_key_hash_change: () -> void

      def key_hash_before_type_cast: () -> ::Integer?

      def key_hash_for_database: () -> ::Integer?

      def value: () -> ::String?

      def value=: (::String?) -> ::String?

      def value?: () -> bool

      def value_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def value_change: () -> [ ::String?, ::String? ]

      def value_will_change!: () -> void

      def value_was: () -> ::String?

      def value_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def value_previous_change: () -> ::Array[::String?]?

      def value_previously_was: () -> ::String?

      def value_before_last_save: () -> ::String?

      def value_change_to_be_saved: () -> ::Array[::String?]?

      def value_in_database: () -> ::String?

      def saved_change_to_value: () -> ::Array[::String?]?

      def saved_change_to_value?: () -> bool

      def will_save_change_to_value?: () -> bool

      def restore_value!: () -> void

      def clear_value_change: () -> void

      def value_before_type_cast: () -> ::String?

      def value_for_database: () -> ::String?
    end
    include ::SolidCache::Entry::GeneratedAttributeMethods
    module ::SolidCache::Entry::GeneratedAliasAttributeMethods
      include ::SolidCache::Entry::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::SolidCache::Entry::GeneratedAliasAttributeMethods

    module ::SolidCache::Entry::GeneratedAssociationMethods
    end
    include ::SolidCache::Entry::GeneratedAssociationMethods

    def self.largest_byte_sizes: (untyped limit) -> ::SolidCache::Entry::ActiveRecord_Relation
    def self.in_key_hash_range: (untyped range) -> ::SolidCache::Entry::ActiveRecord_Relation
    def self.up_to_byte_size: (untyped cutoff) -> ::SolidCache::Entry::ActiveRecord_Relation

    module ::SolidCache::Entry::GeneratedRelationMethods
      def largest_byte_sizes: (untyped limit) -> ::SolidCache::Entry::ActiveRecord_Relation

      def in_key_hash_range: (untyped range) -> ::SolidCache::Entry::ActiveRecord_Relation

      def up_to_byte_size: (untyped cutoff) -> ::SolidCache::Entry::ActiveRecord_Relation
    end

    class ::SolidCache::Entry::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::SolidCache::Entry]
      include ::SolidCache::Entry::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SolidCache::Entry, ::Integer, ::SolidCache::Entry::Validated]
    end

    class ::SolidCache::Entry::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::SolidCache::Entry]
      include ::SolidCache::Entry::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SolidCache::Entry, ::Integer, ::SolidCache::Entry::Validated]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidCache::Entry
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidCache::Entry]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidCache::Entry
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidCache::Entry]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidCache::Entry
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidCache::Entry]
      def reload: () -> ::Array[::SolidCache::Entry]

      def replace: (::Array[::SolidCache::Entry]) -> void
      def delete: (*::SolidCache::Entry | ::Integer) -> ::Array[::SolidCache::Entry]
      def destroy: (*::SolidCache::Entry | ::Integer) -> ::Array[::SolidCache::Entry]
      def <<: (*::SolidCache::Entry | ::Array[::SolidCache::Entry]) -> self
      def prepend: (*::SolidCache::Entry | ::Array[::SolidCache::Entry]) -> self
    end

    class ::SolidCache::Entry::Validated
      def id: () -> ::Integer
      def created_at: () -> ::ActiveSupport::TimeWithZone
    end
  end
end

module ::SolidCache
end
class ::SolidCache::Record < ::ActiveRecord::Base
end
