# resolve-type-names: false

module ::SolidCable
  class ::SolidCable::Message < ::SolidCable::Record
    extend ::ActiveRecord::Base::ClassMethods[::SolidCable::Message, ::SolidCable::Message::ActiveRecord_Relation, ::Integer, ::SolidCable::Message::Validated]

    module ::SolidCable::Message::GeneratedAttributeMethods
      def id: () -> ::Integer?

      def id=: (::Integer?) -> ::Integer?

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer?

      def id_for_database: () -> ::Integer?

      def channel: () -> ::String?

      def channel=: (::String?) -> ::String?

      def channel?: () -> bool

      def channel_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def channel_change: () -> [ ::String?, ::String? ]

      def channel_will_change!: () -> void

      def channel_was: () -> ::String?

      def channel_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def channel_previous_change: () -> ::Array[::String?]?

      def channel_previously_was: () -> ::String?

      def channel_before_last_save: () -> ::String?

      def channel_change_to_be_saved: () -> ::Array[::String?]?

      def channel_in_database: () -> ::String?

      def saved_change_to_channel: () -> ::Array[::String?]?

      def saved_change_to_channel?: () -> bool

      def will_save_change_to_channel?: () -> bool

      def restore_channel!: () -> void

      def clear_channel_change: () -> void

      def channel_before_type_cast: () -> ::String?

      def channel_for_database: () -> ::String?

      def channel_hash: () -> ::Integer?

      def channel_hash=: (::Integer?) -> ::Integer?

      def channel_hash?: () -> bool

      def channel_hash_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def channel_hash_change: () -> [ ::Integer?, ::Integer? ]

      def channel_hash_will_change!: () -> void

      def channel_hash_was: () -> ::Integer?

      def channel_hash_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def channel_hash_previous_change: () -> ::Array[::Integer?]?

      def channel_hash_previously_was: () -> ::Integer?

      def channel_hash_before_last_save: () -> ::Integer?

      def channel_hash_change_to_be_saved: () -> ::Array[::Integer?]?

      def channel_hash_in_database: () -> ::Integer?

      def saved_change_to_channel_hash: () -> ::Array[::Integer?]?

      def saved_change_to_channel_hash?: () -> bool

      def will_save_change_to_channel_hash?: () -> bool

      def restore_channel_hash!: () -> void

      def clear_channel_hash_change: () -> void

      def channel_hash_before_type_cast: () -> ::Integer?

      def channel_hash_for_database: () -> ::Integer?

      def created_at: () -> ::ActiveSupport::TimeWithZone?

      def created_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time?

      def created_at_for_database: () -> ::Time?

      def payload: () -> ::String?

      def payload=: (::String?) -> ::String?

      def payload?: () -> bool

      def payload_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def payload_change: () -> [ ::String?, ::String? ]

      def payload_will_change!: () -> void

      def payload_was: () -> ::String?

      def payload_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def payload_previous_change: () -> ::Array[::String?]?

      def payload_previously_was: () -> ::String?

      def payload_before_last_save: () -> ::String?

      def payload_change_to_be_saved: () -> ::Array[::String?]?

      def payload_in_database: () -> ::String?

      def saved_change_to_payload: () -> ::Array[::String?]?

      def saved_change_to_payload?: () -> bool

      def will_save_change_to_payload?: () -> bool

      def restore_payload!: () -> void

      def clear_payload_change: () -> void

      def payload_before_type_cast: () -> ::String?

      def payload_for_database: () -> ::String?
    end
    include ::SolidCable::Message::GeneratedAttributeMethods
    module ::SolidCable::Message::GeneratedAliasAttributeMethods
      include ::SolidCable::Message::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::SolidCable::Message::GeneratedAliasAttributeMethods

    module ::SolidCable::Message::GeneratedAssociationMethods
    end
    include ::SolidCable::Message::GeneratedAssociationMethods

    def self.trimmable: () -> ::SolidCable::Message::ActiveRecord_Relation
    def self.broadcastable: (untyped channels, untyped last_id) -> ::SolidCable::Message::ActiveRecord_Relation

    module ::SolidCable::Message::GeneratedRelationMethods
      def trimmable: () -> ::SolidCable::Message::ActiveRecord_Relation

      def broadcastable: (untyped channels, untyped last_id) -> ::SolidCable::Message::ActiveRecord_Relation
    end

    class ::SolidCable::Message::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::SolidCable::Message]
      include ::SolidCable::Message::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SolidCable::Message, ::Integer, ::SolidCable::Message::Validated]
    end

    class ::SolidCable::Message::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::SolidCable::Message]
      include ::SolidCable::Message::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SolidCable::Message, ::Integer, ::SolidCable::Message::Validated]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidCable::Message
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidCable::Message]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidCable::Message
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidCable::Message]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidCable::Message
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidCable::Message]
      def reload: () -> ::Array[::SolidCable::Message]

      def replace: (::Array[::SolidCable::Message]) -> void
      def delete: (*::SolidCable::Message | ::Integer) -> ::Array[::SolidCable::Message]
      def destroy: (*::SolidCable::Message | ::Integer) -> ::Array[::SolidCable::Message]
      def <<: (*::SolidCable::Message | ::Array[::SolidCable::Message]) -> self
      def prepend: (*::SolidCable::Message | ::Array[::SolidCable::Message]) -> self
    end

    class ::SolidCable::Message::Validated
      def id: () -> ::Integer
      def created_at: () -> ::ActiveSupport::TimeWithZone
    end
  end
end

module ::SolidCable
end
class ::SolidCable::Record < ::ActiveRecord::Base
end
