---
version: 1
postconditions:
- class: AccountTenanted
  method: resolve_account!
  unconditional:
    ivars:
      "@account": untyped
    self: "::AccountTenanted & ::AccountTenanted::AfterResolveAccount"
- class: ActionPack::WebAuthn::PublicKeyCredential
  method: authenticate
  unconditional:
    ivars:
      "@sign_count": untyped
    self: "::ActionPack::WebAuthn::PublicKeyCredential & ::ActionPack::WebAuthn::PublicKeyCredential::AfterAuthenticate"
- class: ActionPack::WebAuthn::PublicKeyCredential
  method: initialize
  unconditional:
    ivars:
      "@aaguid": "(::String | nil)"
    self: "::ActionPack::WebAuthn::PublicKeyCredential & ::ActionPack::WebAuthn::PublicKeyCredential::AfterInitialize"
- class: BoardsController
  method: create
  unconditional:
    ivars:
      "@board": "::Board"
    self: "::BoardsController & ::BoardsController::AfterCreate"
- class: BoardsController
  method: new
  unconditional:
    ivars:
      "@board": "::Board"
    self: "::BoardsController & ::BoardsController::AfterNew"
- class: BoardsController
  method: set_board
  unconditional:
    ivars:
      "@board": untyped
    self: "::BoardsController & ::BoardsController::AfterSetBoard"
- class: Card::Stallable
  method: remember_to_detect_activity_spikes
  unconditional:
    ivars:
      "@should_detect_activity_spikes": bool
    self: "::Card::Stallable & ::Card::Stallable::AfterRememberToDetectActivitySpikes"
- class: FilterScoped
  method: set_user_filtering
  unconditional:
    ivars:
      "@user_filtering": "::User::Filtering"
    self: "::FilterScoped & ::FilterScoped::AfterSetUserFiltering"
- class: JoinCodesController
  method: set_identity
  unconditional:
    ivars:
      "@identity": "::Identity"
    self: "::JoinCodesController & ::JoinCodesController::AfterSetIdentity"
- class: My::PinsController
  method: index
  unconditional:
    ivars:
      "@pins": untyped
    self: "::My::PinsController & ::My::PinsController::AfterIndex"
- class: Notifications::TraysController
  method: show
  unconditional:
    ivars:
      "@notifications": untyped
    self: "::Notifications::TraysController & ::Notifications::TraysController::AfterShow"
- class: Prompts::CardsController
  method: index
  unconditional:
    ivars:
      "@cards": "::Array[untyped]"
    self: "::Prompts::CardsController & ::Prompts::CardsController::AfterIndex"
- class: SessionsController
  method: new
  unconditional:
    ivars:
      "@authentication_options": "::ActionPack::WebAuthn::PublicKeyCredential::RequestOptions"
    self: "::SessionsController & ::SessionsController::AfterNew"
- class: Signup
  method: create_account
  unconditional:
    ivars:
      "@user": untyped
    self: "::Signup & ::Signup::AfterCreateAccount"
- class: Signup
  method: initialize
  unconditional:
    ivars:
      "@email_address": "(::String | nil)"
    self: "::Signup & ::Signup::AfterInitialize"
- class: Signups::CompletionsController
  method: create
  unconditional:
    ivars:
      "@signup": "::Signup"
    self: "::Signups::CompletionsController & ::Signups::CompletionsController::AfterCreate"
- class: Signups::CompletionsController
  method: new
  unconditional:
    ivars:
      "@signup": "::Signup"
    self: "::Signups::CompletionsController & ::Signups::CompletionsController::AfterNew"
- class: SignupsController
  method: new
  unconditional:
    ivars:
      "@signup": "::Signup"
    self: "::SignupsController & ::SignupsController::AfterNew"
- class: Storage::AttachmentTracking
  method: snapshot_storage_context
  unconditional:
    ivars:
      "@storage_snapshot": "{ :account => untyped, :board => untyped, :recordable
        => untyped }"
    self: "::Storage::AttachmentTracking & ::Storage::AttachmentTracking::AfterSnapshotStorageContext"
- class: ViewTransitions
  method: disable_view_transitions
  unconditional:
    ivars:
      "@disable_view_transition": 'true'
    self: "::ViewTransitions & ::ViewTransitions::AfterDisableViewTransitions"
