# resolve-type-names: false

class ::Webhook < ::ApplicationRecord
  class ::Webhook::DelinquencyTracker < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Webhook::DelinquencyTracker, ::Webhook::DelinquencyTracker::ActiveRecord_Relation, ::String]

    module ::Webhook::DelinquencyTracker::GeneratedAttributeMethods
      def id: () -> ::String

      def id=: (::String) -> ::String

      def id?: () -> bool

      def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def id_change: () -> [ ::String?, ::String? ]

      def id_will_change!: () -> void

      def id_was: () -> ::String?

      def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def id_previous_change: () -> ::Array[::String?]?

      def id_previously_was: () -> ::String?

      def id_before_last_save: () -> ::String?

      def id_change_to_be_saved: () -> ::Array[::String?]?

      def id_in_database: () -> ::String?

      def saved_change_to_id: () -> ::Array[::String?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::String

      def id_for_database: () -> ::String

      def consecutive_failures_count: () -> ::Integer?

      def consecutive_failures_count=: (::Integer?) -> ::Integer?

      def consecutive_failures_count?: () -> bool

      def consecutive_failures_count_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def consecutive_failures_count_change: () -> [ ::Integer?, ::Integer? ]

      def consecutive_failures_count_will_change!: () -> void

      def consecutive_failures_count_was: () -> ::Integer?

      def consecutive_failures_count_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def consecutive_failures_count_previous_change: () -> ::Array[::Integer?]?

      def consecutive_failures_count_previously_was: () -> ::Integer?

      def consecutive_failures_count_before_last_save: () -> ::Integer?

      def consecutive_failures_count_change_to_be_saved: () -> ::Array[::Integer?]?

      def consecutive_failures_count_in_database: () -> ::Integer?

      def saved_change_to_consecutive_failures_count: () -> ::Array[::Integer?]?

      def saved_change_to_consecutive_failures_count?: () -> bool

      def will_save_change_to_consecutive_failures_count?: () -> bool

      def restore_consecutive_failures_count!: () -> void

      def clear_consecutive_failures_count_change: () -> void

      def consecutive_failures_count_before_type_cast: () -> ::Integer?

      def consecutive_failures_count_for_database: () -> ::Integer?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def first_failure_at: () -> ::ActiveSupport::TimeWithZone?

      def first_failure_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

      def first_failure_at?: () -> bool

      def first_failure_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def first_failure_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def first_failure_at_will_change!: () -> void

      def first_failure_at_was: () -> ::ActiveSupport::TimeWithZone?

      def first_failure_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def first_failure_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def first_failure_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def first_failure_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def first_failure_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def first_failure_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_first_failure_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_first_failure_at?: () -> bool

      def will_save_change_to_first_failure_at?: () -> bool

      def restore_first_failure_at!: () -> void

      def clear_first_failure_at_change: () -> void

      def first_failure_at_before_type_cast: () -> ::Time?

      def first_failure_at_for_database: () -> ::Time?

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time

      def webhook_id: () -> ::String

      def webhook_id=: (::String) -> ::String

      def webhook_id?: () -> bool

      def webhook_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def webhook_id_change: () -> [ ::String?, ::String? ]

      def webhook_id_will_change!: () -> void

      def webhook_id_was: () -> ::String?

      def webhook_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def webhook_id_previous_change: () -> ::Array[::String?]?

      def webhook_id_previously_was: () -> ::String?

      def webhook_id_before_last_save: () -> ::String?

      def webhook_id_change_to_be_saved: () -> ::Array[::String?]?

      def webhook_id_in_database: () -> ::String?

      def saved_change_to_webhook_id: () -> ::Array[::String?]?

      def saved_change_to_webhook_id?: () -> bool

      def will_save_change_to_webhook_id?: () -> bool

      def restore_webhook_id!: () -> void

      def clear_webhook_id_change: () -> void

      def webhook_id_before_type_cast: () -> ::String

      def webhook_id_for_database: () -> ::String

      def account_id: () -> ::String

      def account_id=: (::String) -> ::String

      def account_id?: () -> bool

      def account_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_change: () -> [ ::String?, ::String? ]

      def account_id_will_change!: () -> void

      def account_id_was: () -> ::String?

      def account_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_previous_change: () -> ::Array[::String?]?

      def account_id_previously_was: () -> ::String?

      def account_id_before_last_save: () -> ::String?

      def account_id_change_to_be_saved: () -> ::Array[::String?]?

      def account_id_in_database: () -> ::String?

      def saved_change_to_account_id: () -> ::Array[::String?]?

      def saved_change_to_account_id?: () -> bool

      def will_save_change_to_account_id?: () -> bool

      def restore_account_id!: () -> void

      def clear_account_id_change: () -> void

      def account_id_before_type_cast: () -> ::String

      def account_id_for_database: () -> ::String
    end
    include ::Webhook::DelinquencyTracker::GeneratedAttributeMethods
    module ::Webhook::DelinquencyTracker::GeneratedAliasAttributeMethods
      include ::Webhook::DelinquencyTracker::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Webhook::DelinquencyTracker::GeneratedAliasAttributeMethods

    def account: () -> ::Account
    def account=: (::Account?) -> ::Account?
    def reload_account: () -> ::Account?
    def build_account: (untyped) -> ::Account
    def create_account: (untyped) -> ::Account
    def create_account!: (untyped) -> ::Account
    def webhook: () -> ::Webhook
    def webhook=: (::Webhook?) -> ::Webhook?
    def reload_webhook: () -> ::Webhook?
    def build_webhook: (untyped) -> ::Webhook
    def create_webhook: (untyped) -> ::Webhook
    def create_webhook!: (untyped) -> ::Webhook
    module ::Webhook::DelinquencyTracker::GeneratedAssociationMethods
    end
    include ::Webhook::DelinquencyTracker::GeneratedAssociationMethods

    module ::Webhook::DelinquencyTracker::GeneratedRelationMethods
    end

    class ::Webhook::DelinquencyTracker::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Webhook::DelinquencyTracker]
      include ::Webhook::DelinquencyTracker::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Webhook::DelinquencyTracker, ::String]
    end

    class ::Webhook::DelinquencyTracker::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Webhook::DelinquencyTracker]
      include ::Webhook::DelinquencyTracker::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Webhook::DelinquencyTracker, ::String]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Webhook::DelinquencyTracker
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Webhook::DelinquencyTracker]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Webhook::DelinquencyTracker
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Webhook::DelinquencyTracker]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Webhook::DelinquencyTracker
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Webhook::DelinquencyTracker]
      def reload: () -> ::Array[::Webhook::DelinquencyTracker]

      def replace: (::Array[::Webhook::DelinquencyTracker]) -> void
      def delete: (*::Webhook::DelinquencyTracker | ::String) -> ::Array[::Webhook::DelinquencyTracker]
      def destroy: (*::Webhook::DelinquencyTracker | ::String) -> ::Array[::Webhook::DelinquencyTracker]
      def <<: (*::Webhook::DelinquencyTracker | ::Array[::Webhook::DelinquencyTracker]) -> self
      def prepend: (*::Webhook::DelinquencyTracker | ::Array[::Webhook::DelinquencyTracker]) -> self
    end
  end
end

class ::Webhook < ::ApplicationRecord
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Account < ::ApplicationRecord
end
