---
name: zip_kit
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: ea3837a42f43d1403b82622bcf879a2938377bd9
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
