---
name: jwt
version: '2.5'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: ab91d276678ff974ceaf6719c1567c694aa11b6f
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
