# resolve-type-names: false

module ::Search
  class ::Search::Record < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Search::Record, ::Search::Record::ActiveRecord_Relation, ::Integer]

    module ::Search::Record::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def account_id: () -> ::String

      def account_id=: (::String) -> ::String

      def account_id?: () -> bool

      def account_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_change: () -> [ ::String?, ::String? ]

      def account_id_will_change!: () -> void

      def account_id_was: () -> ::String?

      def account_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_previous_change: () -> ::Array[::String?]?

      def account_id_previously_was: () -> ::String?

      def account_id_before_last_save: () -> ::String?

      def account_id_change_to_be_saved: () -> ::Array[::String?]?

      def account_id_in_database: () -> ::String?

      def saved_change_to_account_id: () -> ::Array[::String?]?

      def saved_change_to_account_id?: () -> bool

      def will_save_change_to_account_id?: () -> bool

      def restore_account_id!: () -> void

      def clear_account_id_change: () -> void

      def account_id_before_type_cast: () -> ::String

      def account_id_for_database: () -> ::String

      def searchable_type: () -> ::String

      def searchable_type=: (::String) -> ::String

      def searchable_type?: () -> bool

      def searchable_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def searchable_type_change: () -> [ ::String?, ::String? ]

      def searchable_type_will_change!: () -> void

      def searchable_type_was: () -> ::String?

      def searchable_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def searchable_type_previous_change: () -> ::Array[::String?]?

      def searchable_type_previously_was: () -> ::String?

      def searchable_type_before_last_save: () -> ::String?

      def searchable_type_change_to_be_saved: () -> ::Array[::String?]?

      def searchable_type_in_database: () -> ::String?

      def saved_change_to_searchable_type: () -> ::Array[::String?]?

      def saved_change_to_searchable_type?: () -> bool

      def will_save_change_to_searchable_type?: () -> bool

      def restore_searchable_type!: () -> void

      def clear_searchable_type_change: () -> void

      def searchable_type_before_type_cast: () -> ::String

      def searchable_type_for_database: () -> ::String

      def searchable_id: () -> ::String

      def searchable_id=: (::String) -> ::String

      def searchable_id?: () -> bool

      def searchable_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def searchable_id_change: () -> [ ::String?, ::String? ]

      def searchable_id_will_change!: () -> void

      def searchable_id_was: () -> ::String?

      def searchable_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def searchable_id_previous_change: () -> ::Array[::String?]?

      def searchable_id_previously_was: () -> ::String?

      def searchable_id_before_last_save: () -> ::String?

      def searchable_id_change_to_be_saved: () -> ::Array[::String?]?

      def searchable_id_in_database: () -> ::String?

      def saved_change_to_searchable_id: () -> ::Array[::String?]?

      def saved_change_to_searchable_id?: () -> bool

      def will_save_change_to_searchable_id?: () -> bool

      def restore_searchable_id!: () -> void

      def clear_searchable_id_change: () -> void

      def searchable_id_before_type_cast: () -> ::String

      def searchable_id_for_database: () -> ::String

      def card_id: () -> ::String

      def card_id=: (::String) -> ::String

      def card_id?: () -> bool

      def card_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def card_id_change: () -> [ ::String?, ::String? ]

      def card_id_will_change!: () -> void

      def card_id_was: () -> ::String?

      def card_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def card_id_previous_change: () -> ::Array[::String?]?

      def card_id_previously_was: () -> ::String?

      def card_id_before_last_save: () -> ::String?

      def card_id_change_to_be_saved: () -> ::Array[::String?]?

      def card_id_in_database: () -> ::String?

      def saved_change_to_card_id: () -> ::Array[::String?]?

      def saved_change_to_card_id?: () -> bool

      def will_save_change_to_card_id?: () -> bool

      def restore_card_id!: () -> void

      def clear_card_id_change: () -> void

      def card_id_before_type_cast: () -> ::String

      def card_id_for_database: () -> ::String

      def board_id: () -> ::String

      def board_id=: (::String) -> ::String

      def board_id?: () -> bool

      def board_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def board_id_change: () -> [ ::String?, ::String? ]

      def board_id_will_change!: () -> void

      def board_id_was: () -> ::String?

      def board_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def board_id_previous_change: () -> ::Array[::String?]?

      def board_id_previously_was: () -> ::String?

      def board_id_before_last_save: () -> ::String?

      def board_id_change_to_be_saved: () -> ::Array[::String?]?

      def board_id_in_database: () -> ::String?

      def saved_change_to_board_id: () -> ::Array[::String?]?

      def saved_change_to_board_id?: () -> bool

      def will_save_change_to_board_id?: () -> bool

      def restore_board_id!: () -> void

      def clear_board_id_change: () -> void

      def board_id_before_type_cast: () -> ::String

      def board_id_for_database: () -> ::String

      def title: () -> ::String?

      def title=: (::String?) -> ::String?

      def title?: () -> bool

      def title_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def title_change: () -> [ ::String?, ::String? ]

      def title_will_change!: () -> void

      def title_was: () -> ::String?

      def title_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def title_previous_change: () -> ::Array[::String?]?

      def title_previously_was: () -> ::String?

      def title_before_last_save: () -> ::String?

      def title_change_to_be_saved: () -> ::Array[::String?]?

      def title_in_database: () -> ::String?

      def saved_change_to_title: () -> ::Array[::String?]?

      def saved_change_to_title?: () -> bool

      def will_save_change_to_title?: () -> bool

      def restore_title!: () -> void

      def clear_title_change: () -> void

      def title_before_type_cast: () -> ::String?

      def title_for_database: () -> ::String?

      def content: () -> ::String?

      def content=: (::String?) -> ::String?

      def content?: () -> bool

      def content_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def content_change: () -> [ ::String?, ::String? ]

      def content_will_change!: () -> void

      def content_was: () -> ::String?

      def content_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def content_previous_change: () -> ::Array[::String?]?

      def content_previously_was: () -> ::String?

      def content_before_last_save: () -> ::String?

      def content_change_to_be_saved: () -> ::Array[::String?]?

      def content_in_database: () -> ::String?

      def saved_change_to_content: () -> ::Array[::String?]?

      def saved_change_to_content?: () -> bool

      def will_save_change_to_content?: () -> bool

      def restore_content!: () -> void

      def clear_content_change: () -> void

      def content_before_type_cast: () -> ::String?

      def content_for_database: () -> ::String?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time
    end
    include ::Search::Record::GeneratedAttributeMethods
    module ::Search::Record::GeneratedAliasAttributeMethods
      include ::Search::Record::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Search::Record::GeneratedAliasAttributeMethods

    def search_records_fts: () -> ::Search::Record::SQLite::Fts?
    def search_records_fts=: (::Search::Record::SQLite::Fts?) -> ::Search::Record::SQLite::Fts?
    def build_search_records_fts: (?untyped) -> ::Search::Record::SQLite::Fts
    def create_search_records_fts: (?untyped) -> ::Search::Record::SQLite::Fts
    def create_search_records_fts!: (?untyped) -> ::Search::Record::SQLite::Fts
    def reload_search_records_fts: () -> ::Search::Record::SQLite::Fts?
    def searchable: () -> untyped
    def searchable=: (untyped?) -> untyped?
    def reload_searchable: () -> untyped?
    def card: () -> ::Card
    def card=: (::Card?) -> ::Card?
    def reload_card: () -> ::Card?
    def build_card: (untyped) -> ::Card
    def create_card: (untyped) -> ::Card
    def create_card!: (untyped) -> ::Card
    module ::Search::Record::GeneratedAssociationMethods
    end
    include ::Search::Record::GeneratedAssociationMethods

    def self.matching: (untyped query, untyped account_id) -> ::Search::Record::ActiveRecord_Relation
    def self.for_query: (untyped query, user: untyped) -> ::Search::Record::ActiveRecord_Relation
    def self.search: (untyped query, user: untyped) -> ::Search::Record::ActiveRecord_Relation

    module ::Search::Record::GeneratedRelationMethods
      def matching: (untyped query, untyped account_id) -> ::Search::Record::ActiveRecord_Relation

      def for_query: (untyped query, user: untyped) -> ::Search::Record::ActiveRecord_Relation

      def search: (untyped query, user: untyped) -> ::Search::Record::ActiveRecord_Relation
    end

    class ::Search::Record::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Search::Record]
      include ::Search::Record::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Search::Record, ::Integer]
    end

    class ::Search::Record::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Search::Record]
      include ::Search::Record::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Search::Record, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Search::Record
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Search::Record]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Search::Record
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Search::Record]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Search::Record
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Search::Record]
      def reload: () -> ::Array[::Search::Record]

      def replace: (::Array[::Search::Record]) -> void
      def delete: (*::Search::Record | ::Integer) -> ::Array[::Search::Record]
      def destroy: (*::Search::Record | ::Integer) -> ::Array[::Search::Record]
      def <<: (*::Search::Record | ::Array[::Search::Record]) -> self
      def prepend: (*::Search::Record | ::Array[::Search::Record]) -> self
    end
  end
end

module ::Search
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Search::Record::SQLite::Fts < ::ApplicationRecord
end
class ::Card < ::ApplicationRecord
end
class ::Search::Record < ::ApplicationRecord
end
module ::Search::Record::SQLite
end
