---
name: faker
version: 3.4.2
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 3a4238ece62c77e24dd6c96f47a6bea808c41dbf
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
