# resolve-type-names: false

class ::Board < ::ApplicationRecord
  class ::Board::Publication < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Board::Publication, ::Board::Publication::ActiveRecord_Relation, ::String]

    module ::Board::Publication::GeneratedAttributeMethods
      def id: () -> ::String

      def id=: (::String) -> ::String

      def id?: () -> bool

      def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def id_change: () -> [ ::String?, ::String? ]

      def id_will_change!: () -> void

      def id_was: () -> ::String?

      def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def id_previous_change: () -> ::Array[::String?]?

      def id_previously_was: () -> ::String?

      def id_before_last_save: () -> ::String?

      def id_change_to_be_saved: () -> ::Array[::String?]?

      def id_in_database: () -> ::String?

      def saved_change_to_id: () -> ::Array[::String?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::String

      def id_for_database: () -> ::String

      def board_id: () -> ::String

      def board_id=: (::String) -> ::String

      def board_id?: () -> bool

      def board_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def board_id_change: () -> [ ::String?, ::String? ]

      def board_id_will_change!: () -> void

      def board_id_was: () -> ::String?

      def board_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def board_id_previous_change: () -> ::Array[::String?]?

      def board_id_previously_was: () -> ::String?

      def board_id_before_last_save: () -> ::String?

      def board_id_change_to_be_saved: () -> ::Array[::String?]?

      def board_id_in_database: () -> ::String?

      def saved_change_to_board_id: () -> ::Array[::String?]?

      def saved_change_to_board_id?: () -> bool

      def will_save_change_to_board_id?: () -> bool

      def restore_board_id!: () -> void

      def clear_board_id_change: () -> void

      def board_id_before_type_cast: () -> ::String

      def board_id_for_database: () -> ::String

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def key: () -> ::String?

      def key=: (::String?) -> ::String?

      def key?: () -> bool

      def key_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def key_change: () -> [ ::String?, ::String? ]

      def key_will_change!: () -> void

      def key_was: () -> ::String?

      def key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def key_previous_change: () -> ::Array[::String?]?

      def key_previously_was: () -> ::String?

      def key_before_last_save: () -> ::String?

      def key_change_to_be_saved: () -> ::Array[::String?]?

      def key_in_database: () -> ::String?

      def saved_change_to_key: () -> ::Array[::String?]?

      def saved_change_to_key?: () -> bool

      def will_save_change_to_key?: () -> bool

      def restore_key!: () -> void

      def clear_key_change: () -> void

      def key_before_type_cast: () -> ::String?

      def key_for_database: () -> ::String?

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time

      def account_id: () -> ::String

      def account_id=: (::String) -> ::String

      def account_id?: () -> bool

      def account_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_change: () -> [ ::String?, ::String? ]

      def account_id_will_change!: () -> void

      def account_id_was: () -> ::String?

      def account_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def account_id_previous_change: () -> ::Array[::String?]?

      def account_id_previously_was: () -> ::String?

      def account_id_before_last_save: () -> ::String?

      def account_id_change_to_be_saved: () -> ::Array[::String?]?

      def account_id_in_database: () -> ::String?

      def saved_change_to_account_id: () -> ::Array[::String?]?

      def saved_change_to_account_id?: () -> bool

      def will_save_change_to_account_id?: () -> bool

      def restore_account_id!: () -> void

      def clear_account_id_change: () -> void

      def account_id_before_type_cast: () -> ::String

      def account_id_for_database: () -> ::String
    end
    include ::Board::Publication::GeneratedAttributeMethods
    module ::Board::Publication::GeneratedAliasAttributeMethods
      include ::Board::Publication::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Board::Publication::GeneratedAliasAttributeMethods

    def account: () -> ::Account
    def account=: (::Account?) -> ::Account?
    def reload_account: () -> ::Account?
    def build_account: (untyped) -> ::Account
    def create_account: (untyped) -> ::Account
    def create_account!: (untyped) -> ::Account
    def board: () -> ::Board
    def board=: (::Board?) -> ::Board?
    def reload_board: () -> ::Board?
    def build_board: (untyped) -> ::Board
    def create_board: (untyped) -> ::Board
    def create_board!: (untyped) -> ::Board
    module ::Board::Publication::GeneratedAssociationMethods
    end
    include ::Board::Publication::GeneratedAssociationMethods

    module ::Board::Publication::GeneratedRelationMethods
    end

    class ::Board::Publication::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Board::Publication]
      include ::Board::Publication::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Board::Publication, ::String]
    end

    class ::Board::Publication::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Board::Publication]
      include ::Board::Publication::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Board::Publication, ::String]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Board::Publication
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Board::Publication]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Board::Publication
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Board::Publication]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Board::Publication
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Board::Publication]
      def reload: () -> ::Array[::Board::Publication]

      def replace: (::Array[::Board::Publication]) -> void
      def delete: (*::Board::Publication | ::String) -> ::Array[::Board::Publication]
      def destroy: (*::Board::Publication | ::String) -> ::Array[::Board::Publication]
      def <<: (*::Board::Publication | ::Array[::Board::Publication]) -> self
      def prepend: (*::Board::Publication | ::Array[::Board::Publication]) -> self
    end
  end
end
